// Code generated by ent, DO NOT EDIT.

package channel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channel type in the database.
	Label = "channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIsPublic holds the string denoting the is_public field in the database.
	FieldIsPublic = "is_public"
	// FieldChannelType holds the string denoting the channel_type field in the database.
	FieldChannelType = "channel_type"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeChannelMembers holds the string denoting the channel_members edge name in mutations.
	EdgeChannelMembers = "channel_members"
	// EdgeChannelMessages holds the string denoting the channel_messages edge name in mutations.
	EdgeChannelMessages = "channel_messages"
	// EdgeGroupKeys holds the string denoting the group_keys edge name in mutations.
	EdgeGroupKeys = "group_keys"
	// Table holds the table name of the channel in the database.
	Table = "channels"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "channels"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_owned_channels"
	// ChannelMembersTable is the table that holds the channel_members relation/edge.
	ChannelMembersTable = "channel_members"
	// ChannelMembersInverseTable is the table name for the ChannelMember entity.
	// It exists in this package in order to avoid circular dependency with the "channelmember" package.
	ChannelMembersInverseTable = "channel_members"
	// ChannelMembersColumn is the table column denoting the channel_members relation/edge.
	ChannelMembersColumn = "channel_channel_members"
	// ChannelMessagesTable is the table that holds the channel_messages relation/edge.
	ChannelMessagesTable = "channel_messages"
	// ChannelMessagesInverseTable is the table name for the ChannelMessage entity.
	// It exists in this package in order to avoid circular dependency with the "channelmessage" package.
	ChannelMessagesInverseTable = "channel_messages"
	// ChannelMessagesColumn is the table column denoting the channel_messages relation/edge.
	ChannelMessagesColumn = "channel_channel_messages"
	// GroupKeysTable is the table that holds the group_keys relation/edge.
	GroupKeysTable = "group_keys"
	// GroupKeysInverseTable is the table name for the GroupKey entity.
	// It exists in this package in order to avoid circular dependency with the "groupkey" package.
	GroupKeysInverseTable = "group_keys"
	// GroupKeysColumn is the table column denoting the group_keys relation/edge.
	GroupKeysColumn = "channel_group_keys"
)

// Columns holds all SQL columns for channel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIsPublic,
	FieldChannelType,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "channels"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_owned_channels",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsPublic holds the default value on creation for the "is_public" field.
	DefaultIsPublic bool
	// DefaultChannelType holds the default value on creation for the "channel_type" field.
	DefaultChannelType string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Channel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByIsPublic orders the results by the is_public field.
func ByIsPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublic, opts...).ToFunc()
}

// ByChannelType orders the results by the channel_type field.
func ByChannelType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelMembersCount orders the results by channel_members count.
func ByChannelMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelMembersStep(), opts...)
	}
}

// ByChannelMembers orders the results by channel_members terms.
func ByChannelMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChannelMessagesCount orders the results by channel_messages count.
func ByChannelMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelMessagesStep(), opts...)
	}
}

// ByChannelMessages orders the results by channel_messages terms.
func ByChannelMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupKeysCount orders the results by group_keys count.
func ByGroupKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupKeysStep(), opts...)
	}
}

// ByGroupKeys orders the results by group_keys terms.
func ByGroupKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newChannelMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelMembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelMembersTable, ChannelMembersColumn),
	)
}
func newChannelMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelMessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelMessagesTable, ChannelMessagesColumn),
	)
}
func newGroupKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupKeysTable, GroupKeysColumn),
	)
}
