// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"
	"zuna-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// CipherText applies equality check predicate on the "cipher_text" field. It's identical to CipherTextEQ.
func CipherText(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCipherText, v))
}

// Iv applies equality check predicate on the "iv" field. It's identical to IvEQ.
func Iv(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldIv, v))
}

// AuthTag applies equality check predicate on the "auth_tag" field. It's identical to AuthTagEQ.
func AuthTag(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldAuthTag, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSentAt, v))
}

// ReadAt applies equality check predicate on the "read_at" field. It's identical to ReadAtEQ.
func ReadAt(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReadAt, v))
}

// CipherTextEQ applies the EQ predicate on the "cipher_text" field.
func CipherTextEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCipherText, v))
}

// CipherTextNEQ applies the NEQ predicate on the "cipher_text" field.
func CipherTextNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCipherText, v))
}

// CipherTextIn applies the In predicate on the "cipher_text" field.
func CipherTextIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCipherText, vs...))
}

// CipherTextNotIn applies the NotIn predicate on the "cipher_text" field.
func CipherTextNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCipherText, vs...))
}

// CipherTextGT applies the GT predicate on the "cipher_text" field.
func CipherTextGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCipherText, v))
}

// CipherTextGTE applies the GTE predicate on the "cipher_text" field.
func CipherTextGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCipherText, v))
}

// CipherTextLT applies the LT predicate on the "cipher_text" field.
func CipherTextLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCipherText, v))
}

// CipherTextLTE applies the LTE predicate on the "cipher_text" field.
func CipherTextLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCipherText, v))
}

// CipherTextContains applies the Contains predicate on the "cipher_text" field.
func CipherTextContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldCipherText, v))
}

// CipherTextHasPrefix applies the HasPrefix predicate on the "cipher_text" field.
func CipherTextHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldCipherText, v))
}

// CipherTextHasSuffix applies the HasSuffix predicate on the "cipher_text" field.
func CipherTextHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldCipherText, v))
}

// CipherTextEqualFold applies the EqualFold predicate on the "cipher_text" field.
func CipherTextEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldCipherText, v))
}

// CipherTextContainsFold applies the ContainsFold predicate on the "cipher_text" field.
func CipherTextContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldCipherText, v))
}

// IvEQ applies the EQ predicate on the "iv" field.
func IvEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldIv, v))
}

// IvNEQ applies the NEQ predicate on the "iv" field.
func IvNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldIv, v))
}

// IvIn applies the In predicate on the "iv" field.
func IvIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldIv, vs...))
}

// IvNotIn applies the NotIn predicate on the "iv" field.
func IvNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldIv, vs...))
}

// IvGT applies the GT predicate on the "iv" field.
func IvGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldIv, v))
}

// IvGTE applies the GTE predicate on the "iv" field.
func IvGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldIv, v))
}

// IvLT applies the LT predicate on the "iv" field.
func IvLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldIv, v))
}

// IvLTE applies the LTE predicate on the "iv" field.
func IvLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldIv, v))
}

// IvContains applies the Contains predicate on the "iv" field.
func IvContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldIv, v))
}

// IvHasPrefix applies the HasPrefix predicate on the "iv" field.
func IvHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldIv, v))
}

// IvHasSuffix applies the HasSuffix predicate on the "iv" field.
func IvHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldIv, v))
}

// IvEqualFold applies the EqualFold predicate on the "iv" field.
func IvEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldIv, v))
}

// IvContainsFold applies the ContainsFold predicate on the "iv" field.
func IvContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldIv, v))
}

// AuthTagEQ applies the EQ predicate on the "auth_tag" field.
func AuthTagEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldAuthTag, v))
}

// AuthTagNEQ applies the NEQ predicate on the "auth_tag" field.
func AuthTagNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldAuthTag, v))
}

// AuthTagIn applies the In predicate on the "auth_tag" field.
func AuthTagIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldAuthTag, vs...))
}

// AuthTagNotIn applies the NotIn predicate on the "auth_tag" field.
func AuthTagNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldAuthTag, vs...))
}

// AuthTagGT applies the GT predicate on the "auth_tag" field.
func AuthTagGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldAuthTag, v))
}

// AuthTagGTE applies the GTE predicate on the "auth_tag" field.
func AuthTagGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldAuthTag, v))
}

// AuthTagLT applies the LT predicate on the "auth_tag" field.
func AuthTagLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldAuthTag, v))
}

// AuthTagLTE applies the LTE predicate on the "auth_tag" field.
func AuthTagLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldAuthTag, v))
}

// AuthTagContains applies the Contains predicate on the "auth_tag" field.
func AuthTagContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldAuthTag, v))
}

// AuthTagHasPrefix applies the HasPrefix predicate on the "auth_tag" field.
func AuthTagHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldAuthTag, v))
}

// AuthTagHasSuffix applies the HasSuffix predicate on the "auth_tag" field.
func AuthTagHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldAuthTag, v))
}

// AuthTagEqualFold applies the EqualFold predicate on the "auth_tag" field.
func AuthTagEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldAuthTag, v))
}

// AuthTagContainsFold applies the ContainsFold predicate on the "auth_tag" field.
func AuthTagContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldAuthTag, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldSentAt, v))
}

// ReadAtEQ applies the EQ predicate on the "read_at" field.
func ReadAtEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReadAt, v))
}

// ReadAtNEQ applies the NEQ predicate on the "read_at" field.
func ReadAtNEQ(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReadAt, v))
}

// ReadAtIn applies the In predicate on the "read_at" field.
func ReadAtIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReadAt, vs...))
}

// ReadAtNotIn applies the NotIn predicate on the "read_at" field.
func ReadAtNotIn(vs ...time.Time) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReadAt, vs...))
}

// ReadAtGT applies the GT predicate on the "read_at" field.
func ReadAtGT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReadAt, v))
}

// ReadAtGTE applies the GTE predicate on the "read_at" field.
func ReadAtGTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReadAt, v))
}

// ReadAtLT applies the LT predicate on the "read_at" field.
func ReadAtLT(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReadAt, v))
}

// ReadAtLTE applies the LTE predicate on the "read_at" field.
func ReadAtLTE(v time.Time) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReadAt, v))
}

// ReadAtIsNil applies the IsNil predicate on the "read_at" field.
func ReadAtIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldReadAt))
}

// ReadAtNotNil applies the NotNil predicate on the "read_at" field.
func ReadAtNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldReadAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChat applies the HasEdge predicate on the "chat" edge.
func HasChat() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChatTable, ChatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatWith applies the HasEdge predicate on the "chat" edge with a given conditions (other predicates).
func HasChatWith(preds ...predicate.Chat) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newChatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
