// Code generated by ent, DO NOT EDIT.

package channelmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelmessage type in the database.
	Label = "channel_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientMessageID holds the string denoting the client_message_id field in the database.
	FieldClientMessageID = "client_message_id"
	// FieldCipherText holds the string denoting the cipher_text field in the database.
	FieldCipherText = "cipher_text"
	// FieldIv holds the string denoting the iv field in the database.
	FieldIv = "iv"
	// FieldAuthTag holds the string denoting the auth_tag field in the database.
	FieldAuthTag = "auth_tag"
	// FieldSentAt holds the string denoting the sent_at field in the database.
	FieldSentAt = "sent_at"
	// EdgeSender holds the string denoting the sender edge name in mutations.
	EdgeSender = "sender"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgeAttachment holds the string denoting the attachment edge name in mutations.
	EdgeAttachment = "attachment"
	// Table holds the table name of the channelmessage in the database.
	Table = "channel_messages"
	// SenderTable is the table that holds the sender relation/edge.
	SenderTable = "channel_messages"
	// SenderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	SenderInverseTable = "users"
	// SenderColumn is the table column denoting the sender relation/edge.
	SenderColumn = "user_channel_messages_sent"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "channel_messages"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_channel_messages"
	// AttachmentTable is the table that holds the attachment relation/edge.
	AttachmentTable = "attachments"
	// AttachmentInverseTable is the table name for the Attachment entity.
	// It exists in this package in order to avoid circular dependency with the "attachment" package.
	AttachmentInverseTable = "attachments"
	// AttachmentColumn is the table column denoting the attachment relation/edge.
	AttachmentColumn = "channel_message_attachment"
)

// Columns holds all SQL columns for channelmessage fields.
var Columns = []string{
	FieldID,
	FieldClientMessageID,
	FieldCipherText,
	FieldIv,
	FieldAuthTag,
	FieldSentAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "channel_messages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"channel_channel_messages",
	"user_channel_messages_sent",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSentAt holds the default value on creation for the "sent_at" field.
	DefaultSentAt func() time.Time
)

// OrderOption defines the ordering options for the ChannelMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClientMessageID orders the results by the client_message_id field.
func ByClientMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientMessageID, opts...).ToFunc()
}

// ByCipherText orders the results by the cipher_text field.
func ByCipherText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCipherText, opts...).ToFunc()
}

// ByIv orders the results by the iv field.
func ByIv(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIv, opts...).ToFunc()
}

// ByAuthTag orders the results by the auth_tag field.
func ByAuthTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthTag, opts...).ToFunc()
}

// BySentAt orders the results by the sent_at field.
func BySentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentAt, opts...).ToFunc()
}

// BySenderField orders the results by sender field.
func BySenderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSenderStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByAttachmentField orders the results by attachment field.
func ByAttachmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentStep(), sql.OrderByField(field, opts...))
	}
}
func newSenderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SenderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
	)
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newAttachmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, AttachmentTable, AttachmentColumn),
	)
}
