// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"zuna.chat/zuna-server/ent/attachment"
	"zuna.chat/zuna-server/ent/message"
	"zuna.chat/zuna-server/ent/predicate"
	"zuna.chat/zuna-server/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttachmentUpdate is the builder for updating Attachment entities.
type AttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *AttachmentMutation
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (_u *AttachmentUpdate) Where(ps ...predicate.Attachment) *AttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AttachmentUpdate) SetMetadata(v string) *AttachmentUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableMetadata(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// SetMetadataIv sets the "metadata_iv" field.
func (_u *AttachmentUpdate) SetMetadataIv(v string) *AttachmentUpdate {
	_u.mutation.SetMetadataIv(v)
	return _u
}

// SetNillableMetadataIv sets the "metadata_iv" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableMetadataIv(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetMetadataIv(*v)
	}
	return _u
}

// SetMetadataAuthTag sets the "metadata_auth_tag" field.
func (_u *AttachmentUpdate) SetMetadataAuthTag(v string) *AttachmentUpdate {
	_u.mutation.SetMetadataAuthTag(v)
	return _u
}

// SetNillableMetadataAuthTag sets the "metadata_auth_tag" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableMetadataAuthTag(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetMetadataAuthTag(*v)
	}
	return _u
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_u *AttachmentUpdate) SetMessageID(id int64) *AttachmentUpdate {
	_u.mutation.SetMessageID(id)
	return _u
}

// SetNillableMessageID sets the "message" edge to the Message entity by ID if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableMessageID(id *int64) *AttachmentUpdate {
	if id != nil {
		_u = _u.SetMessageID(*id)
	}
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *AttachmentUpdate) SetMessage(v *Message) *AttachmentUpdate {
	return _u.SetMessageID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AttachmentUpdate) SetUserID(id string) *AttachmentUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AttachmentUpdate) SetUser(v *User) *AttachmentUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_u *AttachmentUpdate) Mutation() *AttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *AttachmentUpdate) ClearMessage() *AttachmentUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AttachmentUpdate) ClearUser() *AttachmentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttachmentUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attachment.user"`)
	}
	return nil
}

func (_u *AttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(attachment.FieldMetadata, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataIv(); ok {
		_spec.SetField(attachment.FieldMetadataIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataAuthTag(); ok {
		_spec.SetField(attachment.FieldMetadataAuthTag, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   attachment.MessageTable,
			Columns: []string{attachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   attachment.MessageTable,
			Columns: []string{attachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.UserTable,
			Columns: []string{attachment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.UserTable,
			Columns: []string{attachment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttachmentUpdateOne is the builder for updating a single Attachment entity.
type AttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttachmentMutation
}

// SetMetadata sets the "metadata" field.
func (_u *AttachmentUpdateOne) SetMetadata(v string) *AttachmentUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableMetadata(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// SetMetadataIv sets the "metadata_iv" field.
func (_u *AttachmentUpdateOne) SetMetadataIv(v string) *AttachmentUpdateOne {
	_u.mutation.SetMetadataIv(v)
	return _u
}

// SetNillableMetadataIv sets the "metadata_iv" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableMetadataIv(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetMetadataIv(*v)
	}
	return _u
}

// SetMetadataAuthTag sets the "metadata_auth_tag" field.
func (_u *AttachmentUpdateOne) SetMetadataAuthTag(v string) *AttachmentUpdateOne {
	_u.mutation.SetMetadataAuthTag(v)
	return _u
}

// SetNillableMetadataAuthTag sets the "metadata_auth_tag" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableMetadataAuthTag(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetMetadataAuthTag(*v)
	}
	return _u
}

// SetMessageID sets the "message" edge to the Message entity by ID.
func (_u *AttachmentUpdateOne) SetMessageID(id int64) *AttachmentUpdateOne {
	_u.mutation.SetMessageID(id)
	return _u
}

// SetNillableMessageID sets the "message" edge to the Message entity by ID if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableMessageID(id *int64) *AttachmentUpdateOne {
	if id != nil {
		_u = _u.SetMessageID(*id)
	}
	return _u
}

// SetMessage sets the "message" edge to the Message entity.
func (_u *AttachmentUpdateOne) SetMessage(v *Message) *AttachmentUpdateOne {
	return _u.SetMessageID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AttachmentUpdateOne) SetUserID(id string) *AttachmentUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AttachmentUpdateOne) SetUser(v *User) *AttachmentUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_u *AttachmentUpdateOne) Mutation() *AttachmentMutation {
	return _u.mutation
}

// ClearMessage clears the "message" edge to the Message entity.
func (_u *AttachmentUpdateOne) ClearMessage() *AttachmentUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AttachmentUpdateOne) ClearUser() *AttachmentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (_u *AttachmentUpdateOne) Where(ps ...predicate.Attachment) *AttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttachmentUpdateOne) Select(field string, fields ...string) *AttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Attachment entity.
func (_u *AttachmentUpdateOne) Save(ctx context.Context) (*Attachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttachmentUpdateOne) SaveX(ctx context.Context) *Attachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttachmentUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attachment.user"`)
	}
	return nil
}

func (_u *AttachmentUpdateOne) sqlSave(ctx context.Context) (_node *Attachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attachment.FieldID)
		for _, f := range fields {
			if !attachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(attachment.FieldMetadata, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataIv(); ok {
		_spec.SetField(attachment.FieldMetadataIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataAuthTag(); ok {
		_spec.SetField(attachment.FieldMetadataAuthTag, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   attachment.MessageTable,
			Columns: []string{attachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   attachment.MessageTable,
			Columns: []string{attachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.UserTable,
			Columns: []string{attachment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.UserTable,
			Columns: []string{attachment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
