// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmessage"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelMessageCreate is the builder for creating a ChannelMessage entity.
type ChannelMessageCreate struct {
	config
	mutation *ChannelMessageMutation
	hooks    []Hook
}

// SetClientMessageID sets the "client_message_id" field.
func (_c *ChannelMessageCreate) SetClientMessageID(v string) *ChannelMessageCreate {
	_c.mutation.SetClientMessageID(v)
	return _c
}

// SetCipherText sets the "cipher_text" field.
func (_c *ChannelMessageCreate) SetCipherText(v string) *ChannelMessageCreate {
	_c.mutation.SetCipherText(v)
	return _c
}

// SetIv sets the "iv" field.
func (_c *ChannelMessageCreate) SetIv(v string) *ChannelMessageCreate {
	_c.mutation.SetIv(v)
	return _c
}

// SetAuthTag sets the "auth_tag" field.
func (_c *ChannelMessageCreate) SetAuthTag(v string) *ChannelMessageCreate {
	_c.mutation.SetAuthTag(v)
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *ChannelMessageCreate) SetSentAt(v time.Time) *ChannelMessageCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *ChannelMessageCreate) SetNillableSentAt(v *time.Time) *ChannelMessageCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelMessageCreate) SetID(v int64) *ChannelMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_c *ChannelMessageCreate) SetSenderID(id string) *ChannelMessageCreate {
	_c.mutation.SetSenderID(id)
	return _c
}

// SetSender sets the "sender" edge to the User entity.
func (_c *ChannelMessageCreate) SetSender(v *User) *ChannelMessageCreate {
	return _c.SetSenderID(v.ID)
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_c *ChannelMessageCreate) SetChannelID(id string) *ChannelMessageCreate {
	_c.mutation.SetChannelID(id)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelMessageCreate) SetChannel(v *Channel) *ChannelMessageCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ChannelMessageMutation object of the builder.
func (_c *ChannelMessageCreate) Mutation() *ChannelMessageMutation {
	return _c.mutation
}

// Save creates the ChannelMessage in the database.
func (_c *ChannelMessageCreate) Save(ctx context.Context) (*ChannelMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelMessageCreate) SaveX(ctx context.Context) *ChannelMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelMessageCreate) defaults() {
	if _, ok := _c.mutation.SentAt(); !ok {
		v := channelmessage.DefaultSentAt()
		_c.mutation.SetSentAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelMessageCreate) check() error {
	if _, ok := _c.mutation.ClientMessageID(); !ok {
		return &ValidationError{Name: "client_message_id", err: errors.New(`ent: missing required field "ChannelMessage.client_message_id"`)}
	}
	if _, ok := _c.mutation.CipherText(); !ok {
		return &ValidationError{Name: "cipher_text", err: errors.New(`ent: missing required field "ChannelMessage.cipher_text"`)}
	}
	if _, ok := _c.mutation.Iv(); !ok {
		return &ValidationError{Name: "iv", err: errors.New(`ent: missing required field "ChannelMessage.iv"`)}
	}
	if _, ok := _c.mutation.AuthTag(); !ok {
		return &ValidationError{Name: "auth_tag", err: errors.New(`ent: missing required field "ChannelMessage.auth_tag"`)}
	}
	if _, ok := _c.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "ChannelMessage.sent_at"`)}
	}
	if len(_c.mutation.SenderIDs()) == 0 {
		return &ValidationError{Name: "sender", err: errors.New(`ent: missing required edge "ChannelMessage.sender"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelMessage.channel"`)}
	}
	return nil
}

func (_c *ChannelMessageCreate) sqlSave(ctx context.Context) (*ChannelMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelMessageCreate) createSpec() (*ChannelMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelmessage.Table, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClientMessageID(); ok {
		_spec.SetField(channelmessage.FieldClientMessageID, field.TypeString, value)
		_node.ClientMessageID = value
	}
	if value, ok := _c.mutation.CipherText(); ok {
		_spec.SetField(channelmessage.FieldCipherText, field.TypeString, value)
		_node.CipherText = value
	}
	if value, ok := _c.mutation.Iv(); ok {
		_spec.SetField(channelmessage.FieldIv, field.TypeString, value)
		_node.Iv = value
	}
	if value, ok := _c.mutation.AuthTag(); ok {
		_spec.SetField(channelmessage.FieldAuthTag, field.TypeString, value)
		_node.AuthTag = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(channelmessage.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.SenderTable,
			Columns: []string{channelmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_channel_messages_sent = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmessage.ChannelTable,
			Columns: []string{channelmessage.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.channel_channel_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelMessageCreateBulk is the builder for creating many ChannelMessage entities in bulk.
type ChannelMessageCreateBulk struct {
	config
	err      error
	builders []*ChannelMessageCreate
}

// Save creates the ChannelMessage entities in the database.
func (_c *ChannelMessageCreateBulk) Save(ctx context.Context) ([]*ChannelMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelMessageCreateBulk) SaveX(ctx context.Context) []*ChannelMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
