// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmember"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelMemberCreate is the builder for creating a ChannelMember entity.
type ChannelMemberCreate struct {
	config
	mutation *ChannelMemberMutation
	hooks    []Hook
}

// SetJoinedAt sets the "joined_at" field.
func (_c *ChannelMemberCreate) SetJoinedAt(v time.Time) *ChannelMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *ChannelMemberCreate) SetNillableJoinedAt(v *time.Time) *ChannelMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetLastReadAt sets the "last_read_at" field.
func (_c *ChannelMemberCreate) SetLastReadAt(v time.Time) *ChannelMemberCreate {
	_c.mutation.SetLastReadAt(v)
	return _c
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_c *ChannelMemberCreate) SetNillableLastReadAt(v *time.Time) *ChannelMemberCreate {
	if v != nil {
		_c.SetLastReadAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelMemberCreate) SetID(v string) *ChannelMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelMemberCreate) SetNillableID(v *string) *ChannelMemberCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_c *ChannelMemberCreate) SetChannelID(id string) *ChannelMemberCreate {
	_c.mutation.SetChannelID(id)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelMemberCreate) SetChannel(v *Channel) *ChannelMemberCreate {
	return _c.SetChannelID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ChannelMemberCreate) SetUserID(id string) *ChannelMemberCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChannelMemberCreate) SetUser(v *User) *ChannelMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ChannelMemberMutation object of the builder.
func (_c *ChannelMemberCreate) Mutation() *ChannelMemberMutation {
	return _c.mutation
}

// Save creates the ChannelMember in the database.
func (_c *ChannelMemberCreate) Save(ctx context.Context) (*ChannelMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelMemberCreate) SaveX(ctx context.Context) *ChannelMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelMemberCreate) defaults() {
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := channelmember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channelmember.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelMemberCreate) check() error {
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "ChannelMember.joined_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelMember.channel"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChannelMember.user"`)}
	}
	return nil
}

func (_c *ChannelMemberCreate) sqlSave(ctx context.Context) (*ChannelMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ChannelMember.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelMemberCreate) createSpec() (*ChannelMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelmember.Table, sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(channelmember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if value, ok := _c.mutation.LastReadAt(); ok {
		_spec.SetField(channelmember.FieldLastReadAt, field.TypeTime, value)
		_node.LastReadAt = &value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.ChannelTable,
			Columns: []string{channelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.channel_channel_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.UserTable,
			Columns: []string{channelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_channel_memberships = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelMemberCreateBulk is the builder for creating many ChannelMember entities in bulk.
type ChannelMemberCreateBulk struct {
	config
	err      error
	builders []*ChannelMemberCreate
}

// Save creates the ChannelMember entities in the database.
func (_c *ChannelMemberCreateBulk) Save(ctx context.Context) ([]*ChannelMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelMemberCreateBulk) SaveX(ctx context.Context) []*ChannelMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
