// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmessage"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelMessage is the model entity for the ChannelMessage schema.
type ChannelMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ClientMessageID holds the value of the "client_message_id" field.
	ClientMessageID string `json:"client_message_id,omitempty"`
	// CipherText holds the value of the "cipher_text" field.
	CipherText string `json:"cipher_text,omitempty"`
	// Iv holds the value of the "iv" field.
	Iv string `json:"iv,omitempty"`
	// AuthTag holds the value of the "auth_tag" field.
	AuthTag string `json:"auth_tag,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt time.Time `json:"sent_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelMessageQuery when eager-loading is set.
	Edges                      ChannelMessageEdges `json:"edges"`
	channel_channel_messages   *string
	user_channel_messages_sent *string
	selectValues               sql.SelectValues
}

// ChannelMessageEdges holds the relations/edges for other nodes in the graph.
type ChannelMessageEdges struct {
	// Sender holds the value of the sender edge.
	Sender *User `json:"sender,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelMessageEdges) SenderOrErr() (*User, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelMessageEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelmessage.FieldID:
			values[i] = new(sql.NullInt64)
		case channelmessage.FieldClientMessageID, channelmessage.FieldCipherText, channelmessage.FieldIv, channelmessage.FieldAuthTag:
			values[i] = new(sql.NullString)
		case channelmessage.FieldSentAt:
			values[i] = new(sql.NullTime)
		case channelmessage.ForeignKeys[0]: // channel_channel_messages
			values[i] = new(sql.NullString)
		case channelmessage.ForeignKeys[1]: // user_channel_messages_sent
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelMessage fields.
func (_m *ChannelMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelmessage.FieldClientMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_message_id", values[i])
			} else if value.Valid {
				_m.ClientMessageID = value.String
			}
		case channelmessage.FieldCipherText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cipher_text", values[i])
			} else if value.Valid {
				_m.CipherText = value.String
			}
		case channelmessage.FieldIv:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field iv", values[i])
			} else if value.Valid {
				_m.Iv = value.String
			}
		case channelmessage.FieldAuthTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_tag", values[i])
			} else if value.Valid {
				_m.AuthTag = value.String
			}
		case channelmessage.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = value.Time
			}
		case channelmessage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_channel_messages", values[i])
			} else if value.Valid {
				_m.channel_channel_messages = new(string)
				*_m.channel_channel_messages = value.String
			}
		case channelmessage.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_channel_messages_sent", values[i])
			} else if value.Valid {
				_m.user_channel_messages_sent = new(string)
				*_m.user_channel_messages_sent = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySender queries the "sender" edge of the ChannelMessage entity.
func (_m *ChannelMessage) QuerySender() *UserQuery {
	return NewChannelMessageClient(_m.config).QuerySender(_m)
}

// QueryChannel queries the "channel" edge of the ChannelMessage entity.
func (_m *ChannelMessage) QueryChannel() *ChannelQuery {
	return NewChannelMessageClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ChannelMessage.
// Note that you need to call ChannelMessage.Unwrap() before calling this method if this ChannelMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelMessage) Update() *ChannelMessageUpdateOne {
	return NewChannelMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelMessage) Unwrap() *ChannelMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_message_id=")
	builder.WriteString(_m.ClientMessageID)
	builder.WriteString(", ")
	builder.WriteString("cipher_text=")
	builder.WriteString(_m.CipherText)
	builder.WriteString(", ")
	builder.WriteString("iv=")
	builder.WriteString(_m.Iv)
	builder.WriteString(", ")
	builder.WriteString("auth_tag=")
	builder.WriteString(_m.AuthTag)
	builder.WriteString(", ")
	builder.WriteString("sent_at=")
	builder.WriteString(_m.SentAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelMessages is a parsable slice of ChannelMessage.
type ChannelMessages []*ChannelMessage
