// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/channelmessage"
	"zuna.chat/zuna-server/ent/predicate"
)

// ChannelMessageDelete is the builder for deleting a ChannelMessage entity.
type ChannelMessageDelete struct {
	config
	hooks    []Hook
	mutation *ChannelMessageMutation
}

// Where appends a list predicates to the ChannelMessageDelete builder.
func (_d *ChannelMessageDelete) Where(ps ...predicate.ChannelMessage) *ChannelMessageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelMessageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelmessage.Table, sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelMessageDeleteOne is the builder for deleting a single ChannelMessage entity.
type ChannelMessageDeleteOne struct {
	_d *ChannelMessageDelete
}

// Where appends a list predicates to the ChannelMessageDelete builder.
func (_d *ChannelMessageDeleteOne) Where(ps ...predicate.ChannelMessage) *ChannelMessageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelmessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelMessageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
