// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmember"
	"zuna.chat/zuna-server/ent/channelmessage"
	"zuna.chat/zuna-server/ent/groupkey"
	"zuna.chat/zuna-server/ent/predicate"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelQuery is the builder for querying Channel entities.
type ChannelQuery struct {
	config
	ctx                 *QueryContext
	order               []channel.OrderOption
	inters              []Interceptor
	predicates          []predicate.Channel
	withOwner           *UserQuery
	withChannelMembers  *ChannelMemberQuery
	withChannelMessages *ChannelMessageQuery
	withGroupKeys       *GroupKeyQuery
	withFKs             bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChannelQuery builder.
func (_q *ChannelQuery) Where(ps ...predicate.Channel) *ChannelQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChannelQuery) Limit(limit int) *ChannelQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChannelQuery) Offset(offset int) *ChannelQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChannelQuery) Unique(unique bool) *ChannelQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChannelQuery) Order(o ...channel.OrderOption) *ChannelQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *ChannelQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channel.OwnerTable, channel.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChannelMembers chains the current query on the "channel_members" edge.
func (_q *ChannelQuery) QueryChannelMembers() *ChannelMemberQuery {
	query := (&ChannelMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(channelmember.Table, channelmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.ChannelMembersTable, channel.ChannelMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChannelMessages chains the current query on the "channel_messages" edge.
func (_q *ChannelQuery) QueryChannelMessages() *ChannelMessageQuery {
	query := (&ChannelMessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(channelmessage.Table, channelmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.ChannelMessagesTable, channel.ChannelMessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroupKeys chains the current query on the "group_keys" edge.
func (_q *ChannelQuery) QueryGroupKeys() *GroupKeyQuery {
	query := (&GroupKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(groupkey.Table, groupkey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.GroupKeysTable, channel.GroupKeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Channel entity from the query.
// Returns a *NotFoundError when no Channel was found.
func (_q *ChannelQuery) First(ctx context.Context) (*Channel, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{channel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChannelQuery) FirstX(ctx context.Context) *Channel {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Channel ID from the query.
// Returns a *NotFoundError when no Channel ID was found.
func (_q *ChannelQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{channel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChannelQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Channel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Channel entity is found.
// Returns a *NotFoundError when no Channel entities are found.
func (_q *ChannelQuery) Only(ctx context.Context) (*Channel, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{channel.Label}
	default:
		return nil, &NotSingularError{channel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChannelQuery) OnlyX(ctx context.Context) *Channel {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Channel ID in the query.
// Returns a *NotSingularError when more than one Channel ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChannelQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{channel.Label}
	default:
		err = &NotSingularError{channel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChannelQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Channels.
func (_q *ChannelQuery) All(ctx context.Context) ([]*Channel, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Channel, *ChannelQuery]()
	return withInterceptors[[]*Channel](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChannelQuery) AllX(ctx context.Context) []*Channel {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Channel IDs.
func (_q *ChannelQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(channel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChannelQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChannelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChannelQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChannelQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChannelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChannelQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChannelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChannelQuery) Clone() *ChannelQuery {
	if _q == nil {
		return nil
	}
	return &ChannelQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]channel.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.Channel{}, _q.predicates...),
		withOwner:           _q.withOwner.Clone(),
		withChannelMembers:  _q.withChannelMembers.Clone(),
		withChannelMessages: _q.withChannelMessages.Clone(),
		withGroupKeys:       _q.withGroupKeys.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithOwner(opts ...func(*UserQuery)) *ChannelQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithChannelMembers tells the query-builder to eager-load the nodes that are connected to
// the "channel_members" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithChannelMembers(opts ...func(*ChannelMemberQuery)) *ChannelQuery {
	query := (&ChannelMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannelMembers = query
	return _q
}

// WithChannelMessages tells the query-builder to eager-load the nodes that are connected to
// the "channel_messages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithChannelMessages(opts ...func(*ChannelMessageQuery)) *ChannelQuery {
	query := (&ChannelMessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannelMessages = query
	return _q
}

// WithGroupKeys tells the query-builder to eager-load the nodes that are connected to
// the "group_keys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithGroupKeys(opts ...func(*GroupKeyQuery)) *ChannelQuery {
	query := (&GroupKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroupKeys = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Channel.Query().
//		GroupBy(channel.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChannelQuery) GroupBy(field string, fields ...string) *ChannelGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChannelGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = channel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Channel.Query().
//		Select(channel.FieldName).
//		Scan(ctx, &v)
func (_q *ChannelQuery) Select(fields ...string) *ChannelSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChannelSelect{ChannelQuery: _q}
	sbuild.label = channel.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChannelSelect configured with the given aggregations.
func (_q *ChannelQuery) Aggregate(fns ...AggregateFunc) *ChannelSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChannelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !channel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChannelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Channel, error) {
	var (
		nodes       = []*Channel{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withOwner != nil,
			_q.withChannelMembers != nil,
			_q.withChannelMessages != nil,
			_q.withGroupKeys != nil,
		}
	)
	if _q.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, channel.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Channel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Channel{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *Channel, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChannelMembers; query != nil {
		if err := _q.loadChannelMembers(ctx, query, nodes,
			func(n *Channel) { n.Edges.ChannelMembers = []*ChannelMember{} },
			func(n *Channel, e *ChannelMember) { n.Edges.ChannelMembers = append(n.Edges.ChannelMembers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChannelMessages; query != nil {
		if err := _q.loadChannelMessages(ctx, query, nodes,
			func(n *Channel) { n.Edges.ChannelMessages = []*ChannelMessage{} },
			func(n *Channel, e *ChannelMessage) { n.Edges.ChannelMessages = append(n.Edges.ChannelMessages, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroupKeys; query != nil {
		if err := _q.loadGroupKeys(ctx, query, nodes,
			func(n *Channel) { n.Edges.GroupKeys = []*GroupKey{} },
			func(n *Channel, e *GroupKey) { n.Edges.GroupKeys = append(n.Edges.GroupKeys, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChannelQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Channel)
	for i := range nodes {
		if nodes[i].user_owned_channels == nil {
			continue
		}
		fk := *nodes[i].user_owned_channels
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_owned_channels" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChannelQuery) loadChannelMembers(ctx context.Context, query *ChannelMemberQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *ChannelMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ChannelMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.ChannelMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.channel_channel_members
		if fk == nil {
			return fmt.Errorf(`foreign-key "channel_channel_members" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_channel_members" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChannelQuery) loadChannelMessages(ctx context.Context, query *ChannelMessageQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *ChannelMessage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ChannelMessage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.ChannelMessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.channel_channel_messages
		if fk == nil {
			return fmt.Errorf(`foreign-key "channel_channel_messages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_channel_messages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChannelQuery) loadGroupKeys(ctx context.Context, query *GroupKeyQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *GroupKey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GroupKey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.GroupKeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.channel_group_keys
		if fk == nil {
			return fmt.Errorf(`foreign-key "channel_group_keys" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_group_keys" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChannelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChannelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for i := range fields {
			if fields[i] != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChannelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(channel.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = channel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChannelGroupBy is the group-by builder for Channel entities.
type ChannelGroupBy struct {
	selector
	build *ChannelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChannelGroupBy) Aggregate(fns ...AggregateFunc) *ChannelGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChannelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelQuery, *ChannelGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChannelGroupBy) sqlScan(ctx context.Context, root *ChannelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChannelSelect is the builder for selecting fields of Channel entities.
type ChannelSelect struct {
	*ChannelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChannelSelect) Aggregate(fns ...AggregateFunc) *ChannelSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChannelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelQuery, *ChannelSelect](ctx, _s.ChannelQuery, _s, _s.inters, v)
}

func (_s *ChannelSelect) sqlScan(ctx context.Context, root *ChannelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
