// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmember"
	"zuna.chat/zuna-server/ent/predicate"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelMemberUpdate is the builder for updating ChannelMember entities.
type ChannelMemberUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMemberMutation
}

// Where appends a list predicates to the ChannelMemberUpdate builder.
func (_u *ChannelMemberUpdate) Where(ps ...predicate.ChannelMember) *ChannelMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ChannelMemberUpdate) SetJoinedAt(v time.Time) *ChannelMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ChannelMemberUpdate) SetNillableJoinedAt(v *time.Time) *ChannelMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLastReadAt sets the "last_read_at" field.
func (_u *ChannelMemberUpdate) SetLastReadAt(v time.Time) *ChannelMemberUpdate {
	_u.mutation.SetLastReadAt(v)
	return _u
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_u *ChannelMemberUpdate) SetNillableLastReadAt(v *time.Time) *ChannelMemberUpdate {
	if v != nil {
		_u.SetLastReadAt(*v)
	}
	return _u
}

// ClearLastReadAt clears the value of the "last_read_at" field.
func (_u *ChannelMemberUpdate) ClearLastReadAt() *ChannelMemberUpdate {
	_u.mutation.ClearLastReadAt()
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *ChannelMemberUpdate) SetChannelID(id string) *ChannelMemberUpdate {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelMemberUpdate) SetChannel(v *Channel) *ChannelMemberUpdate {
	return _u.SetChannelID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ChannelMemberUpdate) SetUserID(id string) *ChannelMemberUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChannelMemberUpdate) SetUser(v *User) *ChannelMemberUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChannelMemberMutation object of the builder.
func (_u *ChannelMemberUpdate) Mutation() *ChannelMemberMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelMemberUpdate) ClearChannel() *ChannelMemberUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChannelMemberUpdate) ClearUser() *ChannelMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMemberUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMember.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMember.user"`)
	}
	return nil
}

func (_u *ChannelMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmember.Table, channelmember.Columns, sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(channelmember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastReadAt(); ok {
		_spec.SetField(channelmember.FieldLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.LastReadAtCleared() {
		_spec.ClearField(channelmember.FieldLastReadAt, field.TypeTime)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.ChannelTable,
			Columns: []string{channelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.ChannelTable,
			Columns: []string{channelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.UserTable,
			Columns: []string{channelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.UserTable,
			Columns: []string{channelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelMemberUpdateOne is the builder for updating a single ChannelMember entity.
type ChannelMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMemberMutation
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ChannelMemberUpdateOne) SetJoinedAt(v time.Time) *ChannelMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ChannelMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *ChannelMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLastReadAt sets the "last_read_at" field.
func (_u *ChannelMemberUpdateOne) SetLastReadAt(v time.Time) *ChannelMemberUpdateOne {
	_u.mutation.SetLastReadAt(v)
	return _u
}

// SetNillableLastReadAt sets the "last_read_at" field if the given value is not nil.
func (_u *ChannelMemberUpdateOne) SetNillableLastReadAt(v *time.Time) *ChannelMemberUpdateOne {
	if v != nil {
		_u.SetLastReadAt(*v)
	}
	return _u
}

// ClearLastReadAt clears the value of the "last_read_at" field.
func (_u *ChannelMemberUpdateOne) ClearLastReadAt() *ChannelMemberUpdateOne {
	_u.mutation.ClearLastReadAt()
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *ChannelMemberUpdateOne) SetChannelID(id string) *ChannelMemberUpdateOne {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelMemberUpdateOne) SetChannel(v *Channel) *ChannelMemberUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ChannelMemberUpdateOne) SetUserID(id string) *ChannelMemberUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChannelMemberUpdateOne) SetUser(v *User) *ChannelMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChannelMemberMutation object of the builder.
func (_u *ChannelMemberUpdateOne) Mutation() *ChannelMemberMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelMemberUpdateOne) ClearChannel() *ChannelMemberUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChannelMemberUpdateOne) ClearUser() *ChannelMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ChannelMemberUpdate builder.
func (_u *ChannelMemberUpdateOne) Where(ps ...predicate.ChannelMember) *ChannelMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelMemberUpdateOne) Select(field string, fields ...string) *ChannelMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelMember entity.
func (_u *ChannelMemberUpdateOne) Save(ctx context.Context) (*ChannelMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMemberUpdateOne) SaveX(ctx context.Context) *ChannelMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMemberUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMember.channel"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMember.user"`)
	}
	return nil
}

func (_u *ChannelMemberUpdateOne) sqlSave(ctx context.Context) (_node *ChannelMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmember.Table, channelmember.Columns, sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelmember.FieldID)
		for _, f := range fields {
			if !channelmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(channelmember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastReadAt(); ok {
		_spec.SetField(channelmember.FieldLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.LastReadAtCleared() {
		_spec.ClearField(channelmember.FieldLastReadAt, field.TypeTime)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.ChannelTable,
			Columns: []string{channelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.ChannelTable,
			Columns: []string{channelmember.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.UserTable,
			Columns: []string{channelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelmember.UserTable,
			Columns: []string{channelmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
