// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmember"
	"zuna.chat/zuna-server/ent/channelmessage"
	"zuna.chat/zuna-server/ent/groupkey"
	"zuna.chat/zuna-server/ent/predicate"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMutation
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdate) SetName(v string) *ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ChannelUpdate) SetIsPublic(v bool) *ChannelUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableIsPublic(v *bool) *ChannelUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetChannelType sets the "channel_type" field.
func (_u *ChannelUpdate) SetChannelType(v string) *ChannelUpdate {
	_u.mutation.SetChannelType(v)
	return _u
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableChannelType(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetChannelType(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChannelUpdate) SetCreatedAt(v time.Time) *ChannelUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableCreatedAt(v *time.Time) *ChannelUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ChannelUpdate) SetOwnerID(id string) *ChannelUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ChannelUpdate) SetOwner(v *User) *ChannelUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddChannelMemberIDs adds the "channel_members" edge to the ChannelMember entity by IDs.
func (_u *ChannelUpdate) AddChannelMemberIDs(ids ...string) *ChannelUpdate {
	_u.mutation.AddChannelMemberIDs(ids...)
	return _u
}

// AddChannelMembers adds the "channel_members" edges to the ChannelMember entity.
func (_u *ChannelUpdate) AddChannelMembers(v ...*ChannelMember) *ChannelUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMemberIDs(ids...)
}

// AddChannelMessageIDs adds the "channel_messages" edge to the ChannelMessage entity by IDs.
func (_u *ChannelUpdate) AddChannelMessageIDs(ids ...int64) *ChannelUpdate {
	_u.mutation.AddChannelMessageIDs(ids...)
	return _u
}

// AddChannelMessages adds the "channel_messages" edges to the ChannelMessage entity.
func (_u *ChannelUpdate) AddChannelMessages(v ...*ChannelMessage) *ChannelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMessageIDs(ids...)
}

// AddGroupKeyIDs adds the "group_keys" edge to the GroupKey entity by IDs.
func (_u *ChannelUpdate) AddGroupKeyIDs(ids ...string) *ChannelUpdate {
	_u.mutation.AddGroupKeyIDs(ids...)
	return _u
}

// AddGroupKeys adds the "group_keys" edges to the GroupKey entity.
func (_u *ChannelUpdate) AddGroupKeys(v ...*GroupKey) *ChannelUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupKeyIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdate) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ChannelUpdate) ClearOwner() *ChannelUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearChannelMembers clears all "channel_members" edges to the ChannelMember entity.
func (_u *ChannelUpdate) ClearChannelMembers() *ChannelUpdate {
	_u.mutation.ClearChannelMembers()
	return _u
}

// RemoveChannelMemberIDs removes the "channel_members" edge to ChannelMember entities by IDs.
func (_u *ChannelUpdate) RemoveChannelMemberIDs(ids ...string) *ChannelUpdate {
	_u.mutation.RemoveChannelMemberIDs(ids...)
	return _u
}

// RemoveChannelMembers removes "channel_members" edges to ChannelMember entities.
func (_u *ChannelUpdate) RemoveChannelMembers(v ...*ChannelMember) *ChannelUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMemberIDs(ids...)
}

// ClearChannelMessages clears all "channel_messages" edges to the ChannelMessage entity.
func (_u *ChannelUpdate) ClearChannelMessages() *ChannelUpdate {
	_u.mutation.ClearChannelMessages()
	return _u
}

// RemoveChannelMessageIDs removes the "channel_messages" edge to ChannelMessage entities by IDs.
func (_u *ChannelUpdate) RemoveChannelMessageIDs(ids ...int64) *ChannelUpdate {
	_u.mutation.RemoveChannelMessageIDs(ids...)
	return _u
}

// RemoveChannelMessages removes "channel_messages" edges to ChannelMessage entities.
func (_u *ChannelUpdate) RemoveChannelMessages(v ...*ChannelMessage) *ChannelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMessageIDs(ids...)
}

// ClearGroupKeys clears all "group_keys" edges to the GroupKey entity.
func (_u *ChannelUpdate) ClearGroupKeys() *ChannelUpdate {
	_u.mutation.ClearGroupKeys()
	return _u
}

// RemoveGroupKeyIDs removes the "group_keys" edge to GroupKey entities by IDs.
func (_u *ChannelUpdate) RemoveGroupKeyIDs(ids ...string) *ChannelUpdate {
	_u.mutation.RemoveGroupKeyIDs(ids...)
	return _u
}

// RemoveGroupKeys removes "group_keys" edges to GroupKey entities.
func (_u *ChannelUpdate) RemoveGroupKeys(v ...*GroupKey) *ChannelUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupKeyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Channel.owner"`)
	}
	return nil
}

func (_u *ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(channel.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChannelType(); ok {
		_spec.SetField(channel.FieldChannelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(channel.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerTable,
			Columns: []string{channel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerTable,
			Columns: []string{channel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMembersTable,
			Columns: []string{channel.ChannelMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMembersIDs(); len(nodes) > 0 && !_u.mutation.ChannelMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMembersTable,
			Columns: []string{channel.ChannelMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMembersTable,
			Columns: []string{channel.ChannelMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMessagesTable,
			Columns: []string{channel.ChannelMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMessagesIDs(); len(nodes) > 0 && !_u.mutation.ChannelMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMessagesTable,
			Columns: []string{channel.ChannelMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMessagesTable,
			Columns: []string{channel.ChannelMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.GroupKeysTable,
			Columns: []string{channel.GroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupKeysIDs(); len(nodes) > 0 && !_u.mutation.GroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.GroupKeysTable,
			Columns: []string{channel.GroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.GroupKeysTable,
			Columns: []string{channel.GroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMutation
}

// SetName sets the "name" field.
func (_u *ChannelUpdateOne) SetName(v string) *ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ChannelUpdateOne) SetIsPublic(v bool) *ChannelUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableIsPublic(v *bool) *ChannelUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetChannelType sets the "channel_type" field.
func (_u *ChannelUpdateOne) SetChannelType(v string) *ChannelUpdateOne {
	_u.mutation.SetChannelType(v)
	return _u
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableChannelType(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetChannelType(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChannelUpdateOne) SetCreatedAt(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableCreatedAt(v *time.Time) *ChannelUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ChannelUpdateOne) SetOwnerID(id string) *ChannelUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ChannelUpdateOne) SetOwner(v *User) *ChannelUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddChannelMemberIDs adds the "channel_members" edge to the ChannelMember entity by IDs.
func (_u *ChannelUpdateOne) AddChannelMemberIDs(ids ...string) *ChannelUpdateOne {
	_u.mutation.AddChannelMemberIDs(ids...)
	return _u
}

// AddChannelMembers adds the "channel_members" edges to the ChannelMember entity.
func (_u *ChannelUpdateOne) AddChannelMembers(v ...*ChannelMember) *ChannelUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMemberIDs(ids...)
}

// AddChannelMessageIDs adds the "channel_messages" edge to the ChannelMessage entity by IDs.
func (_u *ChannelUpdateOne) AddChannelMessageIDs(ids ...int64) *ChannelUpdateOne {
	_u.mutation.AddChannelMessageIDs(ids...)
	return _u
}

// AddChannelMessages adds the "channel_messages" edges to the ChannelMessage entity.
func (_u *ChannelUpdateOne) AddChannelMessages(v ...*ChannelMessage) *ChannelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMessageIDs(ids...)
}

// AddGroupKeyIDs adds the "group_keys" edge to the GroupKey entity by IDs.
func (_u *ChannelUpdateOne) AddGroupKeyIDs(ids ...string) *ChannelUpdateOne {
	_u.mutation.AddGroupKeyIDs(ids...)
	return _u
}

// AddGroupKeys adds the "group_keys" edges to the GroupKey entity.
func (_u *ChannelUpdateOne) AddGroupKeys(v ...*GroupKey) *ChannelUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupKeyIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdateOne) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ChannelUpdateOne) ClearOwner() *ChannelUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearChannelMembers clears all "channel_members" edges to the ChannelMember entity.
func (_u *ChannelUpdateOne) ClearChannelMembers() *ChannelUpdateOne {
	_u.mutation.ClearChannelMembers()
	return _u
}

// RemoveChannelMemberIDs removes the "channel_members" edge to ChannelMember entities by IDs.
func (_u *ChannelUpdateOne) RemoveChannelMemberIDs(ids ...string) *ChannelUpdateOne {
	_u.mutation.RemoveChannelMemberIDs(ids...)
	return _u
}

// RemoveChannelMembers removes "channel_members" edges to ChannelMember entities.
func (_u *ChannelUpdateOne) RemoveChannelMembers(v ...*ChannelMember) *ChannelUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMemberIDs(ids...)
}

// ClearChannelMessages clears all "channel_messages" edges to the ChannelMessage entity.
func (_u *ChannelUpdateOne) ClearChannelMessages() *ChannelUpdateOne {
	_u.mutation.ClearChannelMessages()
	return _u
}

// RemoveChannelMessageIDs removes the "channel_messages" edge to ChannelMessage entities by IDs.
func (_u *ChannelUpdateOne) RemoveChannelMessageIDs(ids ...int64) *ChannelUpdateOne {
	_u.mutation.RemoveChannelMessageIDs(ids...)
	return _u
}

// RemoveChannelMessages removes "channel_messages" edges to ChannelMessage entities.
func (_u *ChannelUpdateOne) RemoveChannelMessages(v ...*ChannelMessage) *ChannelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMessageIDs(ids...)
}

// ClearGroupKeys clears all "group_keys" edges to the GroupKey entity.
func (_u *ChannelUpdateOne) ClearGroupKeys() *ChannelUpdateOne {
	_u.mutation.ClearGroupKeys()
	return _u
}

// RemoveGroupKeyIDs removes the "group_keys" edge to GroupKey entities by IDs.
func (_u *ChannelUpdateOne) RemoveGroupKeyIDs(ids ...string) *ChannelUpdateOne {
	_u.mutation.RemoveGroupKeyIDs(ids...)
	return _u
}

// RemoveGroupKeys removes "group_keys" edges to GroupKey entities.
func (_u *ChannelUpdateOne) RemoveGroupKeys(v ...*GroupKey) *ChannelUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupKeyIDs(ids...)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Channel entity.
func (_u *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Channel.owner"`)
	}
	return nil
}

func (_u *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(channel.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChannelType(); ok {
		_spec.SetField(channel.FieldChannelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(channel.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerTable,
			Columns: []string{channel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerTable,
			Columns: []string{channel.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMembersTable,
			Columns: []string{channel.ChannelMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMembersIDs(); len(nodes) > 0 && !_u.mutation.ChannelMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMembersTable,
			Columns: []string{channel.ChannelMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMembersTable,
			Columns: []string{channel.ChannelMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMessagesTable,
			Columns: []string{channel.ChannelMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMessagesIDs(); len(nodes) > 0 && !_u.mutation.ChannelMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMessagesTable,
			Columns: []string{channel.ChannelMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.ChannelMessagesTable,
			Columns: []string{channel.ChannelMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.GroupKeysTable,
			Columns: []string{channel.GroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupKeysIDs(); len(nodes) > 0 && !_u.mutation.GroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.GroupKeysTable,
			Columns: []string{channel.GroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.GroupKeysTable,
			Columns: []string{channel.GroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
