// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmember"
	"zuna.chat/zuna-server/ent/user"
)

// ChannelMember is the model entity for the ChannelMember schema.
type ChannelMember struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// LastReadAt holds the value of the "last_read_at" field.
	LastReadAt *time.Time `json:"last_read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelMemberQuery when eager-loading is set.
	Edges                    ChannelMemberEdges `json:"edges"`
	channel_channel_members  *string
	user_channel_memberships *string
	selectValues             sql.SelectValues
}

// ChannelMemberEdges holds the relations/edges for other nodes in the graph.
type ChannelMemberEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelMemberEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelmember.FieldID:
			values[i] = new(sql.NullString)
		case channelmember.FieldJoinedAt, channelmember.FieldLastReadAt:
			values[i] = new(sql.NullTime)
		case channelmember.ForeignKeys[0]: // channel_channel_members
			values[i] = new(sql.NullString)
		case channelmember.ForeignKeys[1]: // user_channel_memberships
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelMember fields.
func (_m *ChannelMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelmember.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case channelmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case channelmember.FieldLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_at", values[i])
			} else if value.Valid {
				_m.LastReadAt = new(time.Time)
				*_m.LastReadAt = value.Time
			}
		case channelmember.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_channel_members", values[i])
			} else if value.Valid {
				_m.channel_channel_members = new(string)
				*_m.channel_channel_members = value.String
			}
		case channelmember.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_channel_memberships", values[i])
			} else if value.Valid {
				_m.user_channel_memberships = new(string)
				*_m.user_channel_memberships = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelMember.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelMember entity.
func (_m *ChannelMember) QueryChannel() *ChannelQuery {
	return NewChannelMemberClient(_m.config).QueryChannel(_m)
}

// QueryUser queries the "user" edge of the ChannelMember entity.
func (_m *ChannelMember) QueryUser() *UserQuery {
	return NewChannelMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ChannelMember.
// Note that you need to call ChannelMember.Unwrap() before calling this method if this ChannelMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelMember) Update() *ChannelMemberUpdateOne {
	return NewChannelMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelMember) Unwrap() *ChannelMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelMember) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastReadAt; v != nil {
		builder.WriteString("last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ChannelMembers is a parsable slice of ChannelMember.
type ChannelMembers []*ChannelMember
