// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/groupkey"
	"zuna.chat/zuna-server/ent/user"
)

// GroupKey is the model entity for the GroupKey schema.
type GroupKey struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// EncryptedKey holds the value of the "encrypted_key" field.
	EncryptedKey string `json:"encrypted_key,omitempty"`
	// Iv holds the value of the "iv" field.
	Iv string `json:"iv,omitempty"`
	// AuthTag holds the value of the "auth_tag" field.
	AuthTag string `json:"auth_tag,omitempty"`
	// DeliveredAt holds the value of the "delivered_at" field.
	DeliveredAt *time.Time `json:"delivered_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupKeyQuery when eager-loading is set.
	Edges                    GroupKeyEdges `json:"edges"`
	channel_group_keys       *string
	user_received_group_keys *string
	user_sent_group_keys     *string
	selectValues             sql.SelectValues
}

// GroupKeyEdges holds the relations/edges for other nodes in the graph.
type GroupKeyEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// Recipient holds the value of the recipient edge.
	Recipient *User `json:"recipient,omitempty"`
	// Sender holds the value of the sender edge.
	Sender *User `json:"sender,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupKeyEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// RecipientOrErr returns the Recipient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupKeyEdges) RecipientOrErr() (*User, error) {
	if e.Recipient != nil {
		return e.Recipient, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "recipient"}
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupKeyEdges) SenderOrErr() (*User, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupkey.FieldID, groupkey.FieldEncryptedKey, groupkey.FieldIv, groupkey.FieldAuthTag:
			values[i] = new(sql.NullString)
		case groupkey.FieldDeliveredAt:
			values[i] = new(sql.NullTime)
		case groupkey.ForeignKeys[0]: // channel_group_keys
			values[i] = new(sql.NullString)
		case groupkey.ForeignKeys[1]: // user_received_group_keys
			values[i] = new(sql.NullString)
		case groupkey.ForeignKeys[2]: // user_sent_group_keys
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupKey fields.
func (_m *GroupKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupkey.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case groupkey.FieldEncryptedKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_key", values[i])
			} else if value.Valid {
				_m.EncryptedKey = value.String
			}
		case groupkey.FieldIv:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field iv", values[i])
			} else if value.Valid {
				_m.Iv = value.String
			}
		case groupkey.FieldAuthTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_tag", values[i])
			} else if value.Valid {
				_m.AuthTag = value.String
			}
		case groupkey.FieldDeliveredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delivered_at", values[i])
			} else if value.Valid {
				_m.DeliveredAt = new(time.Time)
				*_m.DeliveredAt = value.Time
			}
		case groupkey.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_group_keys", values[i])
			} else if value.Valid {
				_m.channel_group_keys = new(string)
				*_m.channel_group_keys = value.String
			}
		case groupkey.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_received_group_keys", values[i])
			} else if value.Valid {
				_m.user_received_group_keys = new(string)
				*_m.user_received_group_keys = value.String
			}
		case groupkey.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_sent_group_keys", values[i])
			} else if value.Valid {
				_m.user_sent_group_keys = new(string)
				*_m.user_sent_group_keys = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupKey.
// This includes values selected through modifiers, order, etc.
func (_m *GroupKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the GroupKey entity.
func (_m *GroupKey) QueryChannel() *ChannelQuery {
	return NewGroupKeyClient(_m.config).QueryChannel(_m)
}

// QueryRecipient queries the "recipient" edge of the GroupKey entity.
func (_m *GroupKey) QueryRecipient() *UserQuery {
	return NewGroupKeyClient(_m.config).QueryRecipient(_m)
}

// QuerySender queries the "sender" edge of the GroupKey entity.
func (_m *GroupKey) QuerySender() *UserQuery {
	return NewGroupKeyClient(_m.config).QuerySender(_m)
}

// Update returns a builder for updating this GroupKey.
// Note that you need to call GroupKey.Unwrap() before calling this method if this GroupKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupKey) Update() *GroupKeyUpdateOne {
	return NewGroupKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupKey) Unwrap() *GroupKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupKey) String() string {
	var builder strings.Builder
	builder.WriteString("GroupKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("encrypted_key=")
	builder.WriteString(_m.EncryptedKey)
	builder.WriteString(", ")
	builder.WriteString("iv=")
	builder.WriteString(_m.Iv)
	builder.WriteString(", ")
	builder.WriteString("auth_tag=")
	builder.WriteString(_m.AuthTag)
	builder.WriteString(", ")
	if v := _m.DeliveredAt; v != nil {
		builder.WriteString("delivered_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GroupKeys is a parsable slice of GroupKey.
type GroupKeys []*GroupKey
