// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"zuna-server/ent/attachment"
	"zuna-server/ent/chat"
	"zuna-server/ent/message"
	"zuna-server/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
}

// SetCipherText sets the "cipher_text" field.
func (_c *MessageCreate) SetCipherText(v string) *MessageCreate {
	_c.mutation.SetCipherText(v)
	return _c
}

// SetIv sets the "iv" field.
func (_c *MessageCreate) SetIv(v string) *MessageCreate {
	_c.mutation.SetIv(v)
	return _c
}

// SetAuthTag sets the "auth_tag" field.
func (_c *MessageCreate) SetAuthTag(v string) *MessageCreate {
	_c.mutation.SetAuthTag(v)
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *MessageCreate) SetSentAt(v time.Time) *MessageCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *MessageCreate) SetNillableSentAt(v *time.Time) *MessageCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *MessageCreate) SetReadAt(v time.Time) *MessageCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MessageCreate) SetID(v string) *MessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MessageCreate) SetNillableID(v *string) *MessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *MessageCreate) SetUserID(id string) *MessageCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *MessageCreate) SetUser(v *User) *MessageCreate {
	return _c.SetUserID(v.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (_c *MessageCreate) SetChatID(id string) *MessageCreate {
	_c.mutation.SetChatID(id)
	return _c
}

// SetChat sets the "chat" edge to the Chat entity.
func (_c *MessageCreate) SetChat(v *Chat) *MessageCreate {
	return _c.SetChatID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_c *MessageCreate) AddAttachmentIDs(ids ...string) *MessageCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_c *MessageCreate) AddAttachments(v ...*Attachment) *MessageCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (_c *MessageCreate) Mutation() *MessageMutation {
	return _c.mutation
}

// Save creates the Message in the database.
func (_c *MessageCreate) Save(ctx context.Context) (*Message, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageCreate) defaults() {
	if _, ok := _c.mutation.SentAt(); !ok {
		v := message.DefaultSentAt()
		_c.mutation.SetSentAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := message.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageCreate) check() error {
	if _, ok := _c.mutation.CipherText(); !ok {
		return &ValidationError{Name: "cipher_text", err: errors.New(`ent: missing required field "Message.cipher_text"`)}
	}
	if _, ok := _c.mutation.Iv(); !ok {
		return &ValidationError{Name: "iv", err: errors.New(`ent: missing required field "Message.iv"`)}
	}
	if _, ok := _c.mutation.AuthTag(); !ok {
		return &ValidationError{Name: "auth_tag", err: errors.New(`ent: missing required field "Message.auth_tag"`)}
	}
	if _, ok := _c.mutation.SentAt(); !ok {
		return &ValidationError{Name: "sent_at", err: errors.New(`ent: missing required field "Message.sent_at"`)}
	}
	if _, ok := _c.mutation.ReadAt(); !ok {
		return &ValidationError{Name: "read_at", err: errors.New(`ent: missing required field "Message.read_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Message.user"`)}
	}
	if len(_c.mutation.ChatIDs()) == 0 {
		return &ValidationError{Name: "chat", err: errors.New(`ent: missing required edge "Message.chat"`)}
	}
	return nil
}

func (_c *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Message.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CipherText(); ok {
		_spec.SetField(message.FieldCipherText, field.TypeString, value)
		_node.CipherText = &value
	}
	if value, ok := _c.mutation.Iv(); ok {
		_spec.SetField(message.FieldIv, field.TypeString, value)
		_node.Iv = &value
	}
	if value, ok := _c.mutation.AuthTag(); ok {
		_spec.SetField(message.FieldAuthTag, field.TypeString, value)
		_node.AuthTag = &value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(message.FieldSentAt, field.TypeTime, value)
		_node.SentAt = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(message.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.UserTable,
			Columns: []string{message.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chat_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.AttachmentsTable,
			Columns: []string{message.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
}

// Save creates the Message entities in the database.
func (_c *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Message, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
