// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"zuna.chat/zuna-server/ent/attachment"
	"zuna.chat/zuna-server/ent/chat"
	"zuna.chat/zuna-server/ent/message"
	"zuna.chat/zuna-server/ent/user"
)

// Message is the model entity for the Message schema.
type Message struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CipherText holds the value of the "cipher_text" field.
	CipherText string `json:"cipher_text,omitempty"`
	// Iv holds the value of the "iv" field.
	Iv string `json:"iv,omitempty"`
	// AuthTag holds the value of the "auth_tag" field.
	AuthTag string `json:"auth_tag,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt time.Time `json:"sent_at,omitempty"`
	// ReadAt holds the value of the "read_at" field.
	ReadAt *time.Time `json:"read_at,omitempty"`
	// Pinned holds the value of the "pinned" field.
	Pinned bool `json:"pinned,omitempty"`
	// Modified holds the value of the "modified" field.
	Modified bool `json:"modified,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MessageQuery when eager-loading is set.
	Edges            MessageEdges `json:"edges"`
	chat_messages    *string
	message_reply_to *int64
	user_messages    *string
	selectValues     sql.SelectValues
}

// MessageEdges holds the relations/edges for other nodes in the graph.
type MessageEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Chat holds the value of the chat edge.
	Chat *Chat `json:"chat,omitempty"`
	// Reply holds the value of the reply edge.
	Reply []*Message `json:"reply,omitempty"`
	// ReplyTo holds the value of the reply_to edge.
	ReplyTo *Message `json:"reply_to,omitempty"`
	// Attachment holds the value of the attachment edge.
	Attachment *Attachment `json:"attachment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ChatOrErr returns the Chat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageEdges) ChatOrErr() (*Chat, error) {
	if e.Chat != nil {
		return e.Chat, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: chat.Label}
	}
	return nil, &NotLoadedError{edge: "chat"}
}

// ReplyOrErr returns the Reply value or an error if the edge
// was not loaded in eager-loading.
func (e MessageEdges) ReplyOrErr() ([]*Message, error) {
	if e.loadedTypes[2] {
		return e.Reply, nil
	}
	return nil, &NotLoadedError{edge: "reply"}
}

// ReplyToOrErr returns the ReplyTo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageEdges) ReplyToOrErr() (*Message, error) {
	if e.ReplyTo != nil {
		return e.ReplyTo, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: message.Label}
	}
	return nil, &NotLoadedError{edge: "reply_to"}
}

// AttachmentOrErr returns the Attachment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageEdges) AttachmentOrErr() (*Attachment, error) {
	if e.Attachment != nil {
		return e.Attachment, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: attachment.Label}
	}
	return nil, &NotLoadedError{edge: "attachment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Message) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case message.FieldPinned, message.FieldModified:
			values[i] = new(sql.NullBool)
		case message.FieldID:
			values[i] = new(sql.NullInt64)
		case message.FieldCipherText, message.FieldIv, message.FieldAuthTag:
			values[i] = new(sql.NullString)
		case message.FieldSentAt, message.FieldReadAt:
			values[i] = new(sql.NullTime)
		case message.ForeignKeys[0]: // chat_messages
			values[i] = new(sql.NullString)
		case message.ForeignKeys[1]: // message_reply_to
			values[i] = new(sql.NullInt64)
		case message.ForeignKeys[2]: // user_messages
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Message fields.
func (_m *Message) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case message.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case message.FieldCipherText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cipher_text", values[i])
			} else if value.Valid {
				_m.CipherText = value.String
			}
		case message.FieldIv:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field iv", values[i])
			} else if value.Valid {
				_m.Iv = value.String
			}
		case message.FieldAuthTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_tag", values[i])
			} else if value.Valid {
				_m.AuthTag = value.String
			}
		case message.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = value.Time
			}
		case message.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = new(time.Time)
				*_m.ReadAt = value.Time
			}
		case message.FieldPinned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pinned", values[i])
			} else if value.Valid {
				_m.Pinned = value.Bool
			}
		case message.FieldModified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field modified", values[i])
			} else if value.Valid {
				_m.Modified = value.Bool
			}
		case message.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chat_messages", values[i])
			} else if value.Valid {
				_m.chat_messages = new(string)
				*_m.chat_messages = value.String
			}
		case message.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field message_reply_to", value)
			} else if value.Valid {
				_m.message_reply_to = new(int64)
				*_m.message_reply_to = int64(value.Int64)
			}
		case message.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_messages", values[i])
			} else if value.Valid {
				_m.user_messages = new(string)
				*_m.user_messages = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Message.
// This includes values selected through modifiers, order, etc.
func (_m *Message) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Message entity.
func (_m *Message) QueryUser() *UserQuery {
	return NewMessageClient(_m.config).QueryUser(_m)
}

// QueryChat queries the "chat" edge of the Message entity.
func (_m *Message) QueryChat() *ChatQuery {
	return NewMessageClient(_m.config).QueryChat(_m)
}

// QueryReply queries the "reply" edge of the Message entity.
func (_m *Message) QueryReply() *MessageQuery {
	return NewMessageClient(_m.config).QueryReply(_m)
}

// QueryReplyTo queries the "reply_to" edge of the Message entity.
func (_m *Message) QueryReplyTo() *MessageQuery {
	return NewMessageClient(_m.config).QueryReplyTo(_m)
}

// QueryAttachment queries the "attachment" edge of the Message entity.
func (_m *Message) QueryAttachment() *AttachmentQuery {
	return NewMessageClient(_m.config).QueryAttachment(_m)
}

// Update returns a builder for updating this Message.
// Note that you need to call Message.Unwrap() before calling this method if this Message
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Message) Update() *MessageUpdateOne {
	return NewMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Message entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Message) Unwrap() *Message {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Message is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Message) String() string {
	var builder strings.Builder
	builder.WriteString("Message(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cipher_text=")
	builder.WriteString(_m.CipherText)
	builder.WriteString(", ")
	builder.WriteString("iv=")
	builder.WriteString(_m.Iv)
	builder.WriteString(", ")
	builder.WriteString("auth_tag=")
	builder.WriteString(_m.AuthTag)
	builder.WriteString(", ")
	builder.WriteString("sent_at=")
	builder.WriteString(_m.SentAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReadAt; v != nil {
		builder.WriteString("read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("pinned=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pinned))
	builder.WriteString(", ")
	builder.WriteString("modified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Modified))
	builder.WriteByte(')')
	return builder.String()
}

// Messages is a parsable slice of Message.
type Messages []*Message
