// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"zuna-server/ent/attachment"
	"zuna-server/ent/chat"
	"zuna-server/ent/message"
	"zuna-server/ent/schema"
	"zuna-server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescID is the schema descriptor for id field.
	attachmentDescID := attachmentFields[0].Descriptor()
	// attachment.DefaultID holds the default value on creation for the id field.
	attachment.DefaultID = attachmentDescID.Default.(func() string)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() string)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescSentAt is the schema descriptor for sent_at field.
	messageDescSentAt := messageFields[4].Descriptor()
	// message.DefaultSentAt holds the default value on creation for the sent_at field.
	message.DefaultSentAt = messageDescSentAt.Default.(func() time.Time)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescLastSeen is the schema descriptor for last_seen field.
	userDescLastSeen := userFields[4].Descriptor()
	// user.DefaultLastSeen holds the default value on creation for the last_seen field.
	user.DefaultLastSeen = userDescLastSeen.Default.(func() time.Time)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[5].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[6].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.([]byte)
	// userDescAvatarIv is the schema descriptor for avatar_iv field.
	userDescAvatarIv := userFields[7].Descriptor()
	// user.DefaultAvatarIv holds the default value on creation for the avatar_iv field.
	user.DefaultAvatarIv = userDescAvatarIv.Default.([]byte)
	// userDescAvatarAuthTag is the schema descriptor for avatar_auth_tag field.
	userDescAvatarAuthTag := userFields[8].Descriptor()
	// user.DefaultAvatarAuthTag holds the default value on creation for the avatar_auth_tag field.
	user.DefaultAvatarAuthTag = userDescAvatarAuthTag.Default.([]byte)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
