// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"zuna-server/ent/attachment"
	"zuna-server/ent/chat"
	"zuna-server/ent/message"
	"zuna-server/ent/schema"
	"zuna-server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescID is the schema descriptor for id field.
	attachmentDescID := attachmentFields[0].Descriptor()
	// attachment.DefaultID holds the default value on creation for the id field.
	attachment.DefaultID = attachmentDescID.Default.(func() string)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() string)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescSentAt is the schema descriptor for sent_at field.
	messageDescSentAt := messageFields[4].Descriptor()
	// message.DefaultSentAt holds the default value on creation for the sent_at field.
	message.DefaultSentAt = messageDescSentAt.Default.(func() time.Time)
	// messageDescPinned is the schema descriptor for pinned field.
	messageDescPinned := messageFields[6].Descriptor()
	// message.DefaultPinned holds the default value on creation for the pinned field.
	message.DefaultPinned = messageDescPinned.Default.(bool)
	// messageDescModified is the schema descriptor for modified field.
	messageDescModified := messageFields[7].Descriptor()
	// message.DefaultModified holds the default value on creation for the modified field.
	message.DefaultModified = messageDescModified.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescLastSeen is the schema descriptor for last_seen field.
	userDescLastSeen := userFields[4].Descriptor()
	// user.DefaultLastSeen holds the default value on creation for the last_seen field.
	user.DefaultLastSeen = userDescLastSeen.Default.(func() time.Time)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[5].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescAvatarMime is the schema descriptor for avatar_mime field.
	userDescAvatarMime := userFields[6].Descriptor()
	// user.DefaultAvatarMime holds the default value on creation for the avatar_mime field.
	user.DefaultAvatarMime = userDescAvatarMime.Default.(string)
	// userDescAvatarKey is the schema descriptor for avatar_key field.
	userDescAvatarKey := userFields[7].Descriptor()
	// user.DefaultAvatarKey holds the default value on creation for the avatar_key field.
	user.DefaultAvatarKey = userDescAvatarKey.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
