// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"zuna-server/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// IdentityKey holds the value of the "identity_key" field.
	IdentityKey []byte `json:"identity_key,omitempty"`
	// SigningKey holds the value of the "signing_key" field.
	SigningKey []byte `json:"signing_key,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen time.Time `json:"last_seen,omitempty"`
	// IsAdmin holds the value of the "is_admin" field.
	IsAdmin bool `json:"is_admin,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar []byte `json:"avatar,omitempty"`
	// AvatarIv holds the value of the "avatar_iv" field.
	AvatarIv []byte `json:"avatar_iv,omitempty"`
	// AvatarAuthTag holds the value of the "avatar_auth_tag" field.
	AvatarAuthTag []byte `json:"avatar_auth_tag,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Chats holds the value of the chats edge.
	Chats []*Chat `json:"chats,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChatsOrErr returns the Chats value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChatsOrErr() ([]*Chat, error) {
	if e.loadedTypes[0] {
		return e.Chats, nil
	}
	return nil, &NotLoadedError{edge: "chats"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[1] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIdentityKey, user.FieldSigningKey, user.FieldAvatar, user.FieldAvatarIv, user.FieldAvatarAuthTag:
			values[i] = new([]byte)
		case user.FieldIsAdmin:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldUsername:
			values[i] = new(sql.NullString)
		case user.FieldLastSeen:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldIdentityKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field identity_key", values[i])
			} else if value != nil {
				_m.IdentityKey = *value
			}
		case user.FieldSigningKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field signing_key", values[i])
			} else if value != nil {
				_m.SigningKey = *value
			}
		case user.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = value.Time
			}
		case user.FieldIsAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_admin", values[i])
			} else if value.Valid {
				_m.IsAdmin = value.Bool
			}
		case user.FieldAvatar:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value != nil {
				_m.Avatar = *value
			}
		case user.FieldAvatarIv:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_iv", values[i])
			} else if value != nil {
				_m.AvatarIv = *value
			}
		case user.FieldAvatarAuthTag:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_auth_tag", values[i])
			} else if value != nil {
				_m.AvatarAuthTag = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChats queries the "chats" edge of the User entity.
func (_m *User) QueryChats() *ChatQuery {
	return NewUserClient(_m.config).QueryChats(_m)
}

// QueryMessages queries the "messages" edge of the User entity.
func (_m *User) QueryMessages() *MessageQuery {
	return NewUserClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("identity_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.IdentityKey))
	builder.WriteString(", ")
	builder.WriteString("signing_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.SigningKey))
	builder.WriteString(", ")
	builder.WriteString("last_seen=")
	builder.WriteString(_m.LastSeen.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAdmin))
	builder.WriteString(", ")
	builder.WriteString("avatar=")
	builder.WriteString(fmt.Sprintf("%v", _m.Avatar))
	builder.WriteString(", ")
	builder.WriteString("avatar_iv=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvatarIv))
	builder.WriteString(", ")
	builder.WriteString("avatar_auth_tag=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvatarAuthTag))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
