// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"zuna.chat/zuna-server/ent/attachment"
	"zuna.chat/zuna-server/ent/channel"
	"zuna.chat/zuna-server/ent/channelmember"
	"zuna.chat/zuna-server/ent/channelmessage"
	"zuna.chat/zuna-server/ent/chat"
	"zuna.chat/zuna-server/ent/device"
	"zuna.chat/zuna-server/ent/groupkey"
	"zuna.chat/zuna-server/ent/message"
	"zuna.chat/zuna-server/ent/predicate"
	"zuna.chat/zuna-server/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIdentityKey sets the "identity_key" field.
func (_u *UserUpdate) SetIdentityKey(v string) *UserUpdate {
	_u.mutation.SetIdentityKey(v)
	return _u
}

// SetNillableIdentityKey sets the "identity_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIdentityKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetIdentityKey(*v)
	}
	return _u
}

// SetSigningKey sets the "signing_key" field.
func (_u *UserUpdate) SetSigningKey(v string) *UserUpdate {
	_u.mutation.SetSigningKey(v)
	return _u
}

// SetNillableSigningKey sets the "signing_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSigningKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetSigningKey(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *UserUpdate) SetLastSeen(v time.Time) *UserUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastSeen(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *UserUpdate) SetIsAdmin(v bool) *UserUpdate {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsAdmin(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetAvatarMime sets the "avatar_mime" field.
func (_u *UserUpdate) SetAvatarMime(v string) *UserUpdate {
	_u.mutation.SetAvatarMime(v)
	return _u
}

// SetNillableAvatarMime sets the "avatar_mime" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarMime(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarMime(*v)
	}
	return _u
}

// SetAvatarKey sets the "avatar_key" field.
func (_u *UserUpdate) SetAvatarKey(v string) *UserUpdate {
	_u.mutation.SetAvatarKey(v)
	return _u
}

// SetNillableAvatarKey sets the "avatar_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarKey(*v)
	}
	return _u
}

// AddChatIDs adds the "chats" edge to the Chat entity by IDs.
func (_u *UserUpdate) AddChatIDs(ids ...string) *UserUpdate {
	_u.mutation.AddChatIDs(ids...)
	return _u
}

// AddChats adds the "chats" edges to the Chat entity.
func (_u *UserUpdate) AddChats(v ...*Chat) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *UserUpdate) AddMessageIDs(ids ...int64) *UserUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *UserUpdate) AddMessages(v ...*Message) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *UserUpdate) AddAttachmentIDs(ids ...string) *UserUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *UserUpdate) AddAttachments(v ...*Attachment) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_u *UserUpdate) AddDeviceIDs(ids ...int64) *UserUpdate {
	_u.mutation.AddDeviceIDs(ids...)
	return _u
}

// AddDevices adds the "devices" edges to the Device entity.
func (_u *UserUpdate) AddDevices(v ...*Device) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeviceIDs(ids...)
}

// AddOwnedChannelIDs adds the "owned_channels" edge to the Channel entity by IDs.
func (_u *UserUpdate) AddOwnedChannelIDs(ids ...string) *UserUpdate {
	_u.mutation.AddOwnedChannelIDs(ids...)
	return _u
}

// AddOwnedChannels adds the "owned_channels" edges to the Channel entity.
func (_u *UserUpdate) AddOwnedChannels(v ...*Channel) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedChannelIDs(ids...)
}

// AddChannelMembershipIDs adds the "channel_memberships" edge to the ChannelMember entity by IDs.
func (_u *UserUpdate) AddChannelMembershipIDs(ids ...string) *UserUpdate {
	_u.mutation.AddChannelMembershipIDs(ids...)
	return _u
}

// AddChannelMemberships adds the "channel_memberships" edges to the ChannelMember entity.
func (_u *UserUpdate) AddChannelMemberships(v ...*ChannelMember) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMembershipIDs(ids...)
}

// AddChannelMessagesSentIDs adds the "channel_messages_sent" edge to the ChannelMessage entity by IDs.
func (_u *UserUpdate) AddChannelMessagesSentIDs(ids ...int64) *UserUpdate {
	_u.mutation.AddChannelMessagesSentIDs(ids...)
	return _u
}

// AddChannelMessagesSent adds the "channel_messages_sent" edges to the ChannelMessage entity.
func (_u *UserUpdate) AddChannelMessagesSent(v ...*ChannelMessage) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMessagesSentIDs(ids...)
}

// AddReceivedGroupKeyIDs adds the "received_group_keys" edge to the GroupKey entity by IDs.
func (_u *UserUpdate) AddReceivedGroupKeyIDs(ids ...string) *UserUpdate {
	_u.mutation.AddReceivedGroupKeyIDs(ids...)
	return _u
}

// AddReceivedGroupKeys adds the "received_group_keys" edges to the GroupKey entity.
func (_u *UserUpdate) AddReceivedGroupKeys(v ...*GroupKey) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReceivedGroupKeyIDs(ids...)
}

// AddSentGroupKeyIDs adds the "sent_group_keys" edge to the GroupKey entity by IDs.
func (_u *UserUpdate) AddSentGroupKeyIDs(ids ...string) *UserUpdate {
	_u.mutation.AddSentGroupKeyIDs(ids...)
	return _u
}

// AddSentGroupKeys adds the "sent_group_keys" edges to the GroupKey entity.
func (_u *UserUpdate) AddSentGroupKeys(v ...*GroupKey) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentGroupKeyIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearChats clears all "chats" edges to the Chat entity.
func (_u *UserUpdate) ClearChats() *UserUpdate {
	_u.mutation.ClearChats()
	return _u
}

// RemoveChatIDs removes the "chats" edge to Chat entities by IDs.
func (_u *UserUpdate) RemoveChatIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveChatIDs(ids...)
	return _u
}

// RemoveChats removes "chats" edges to Chat entities.
func (_u *UserUpdate) RemoveChats(v ...*Chat) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *UserUpdate) ClearMessages() *UserUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *UserUpdate) RemoveMessageIDs(ids ...int64) *UserUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *UserUpdate) RemoveMessages(v ...*Message) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *UserUpdate) ClearAttachments() *UserUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *UserUpdate) RemoveAttachmentIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *UserUpdate) RemoveAttachments(v ...*Attachment) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearDevices clears all "devices" edges to the Device entity.
func (_u *UserUpdate) ClearDevices() *UserUpdate {
	_u.mutation.ClearDevices()
	return _u
}

// RemoveDeviceIDs removes the "devices" edge to Device entities by IDs.
func (_u *UserUpdate) RemoveDeviceIDs(ids ...int64) *UserUpdate {
	_u.mutation.RemoveDeviceIDs(ids...)
	return _u
}

// RemoveDevices removes "devices" edges to Device entities.
func (_u *UserUpdate) RemoveDevices(v ...*Device) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeviceIDs(ids...)
}

// ClearOwnedChannels clears all "owned_channels" edges to the Channel entity.
func (_u *UserUpdate) ClearOwnedChannels() *UserUpdate {
	_u.mutation.ClearOwnedChannels()
	return _u
}

// RemoveOwnedChannelIDs removes the "owned_channels" edge to Channel entities by IDs.
func (_u *UserUpdate) RemoveOwnedChannelIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveOwnedChannelIDs(ids...)
	return _u
}

// RemoveOwnedChannels removes "owned_channels" edges to Channel entities.
func (_u *UserUpdate) RemoveOwnedChannels(v ...*Channel) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedChannelIDs(ids...)
}

// ClearChannelMemberships clears all "channel_memberships" edges to the ChannelMember entity.
func (_u *UserUpdate) ClearChannelMemberships() *UserUpdate {
	_u.mutation.ClearChannelMemberships()
	return _u
}

// RemoveChannelMembershipIDs removes the "channel_memberships" edge to ChannelMember entities by IDs.
func (_u *UserUpdate) RemoveChannelMembershipIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveChannelMembershipIDs(ids...)
	return _u
}

// RemoveChannelMemberships removes "channel_memberships" edges to ChannelMember entities.
func (_u *UserUpdate) RemoveChannelMemberships(v ...*ChannelMember) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMembershipIDs(ids...)
}

// ClearChannelMessagesSent clears all "channel_messages_sent" edges to the ChannelMessage entity.
func (_u *UserUpdate) ClearChannelMessagesSent() *UserUpdate {
	_u.mutation.ClearChannelMessagesSent()
	return _u
}

// RemoveChannelMessagesSentIDs removes the "channel_messages_sent" edge to ChannelMessage entities by IDs.
func (_u *UserUpdate) RemoveChannelMessagesSentIDs(ids ...int64) *UserUpdate {
	_u.mutation.RemoveChannelMessagesSentIDs(ids...)
	return _u
}

// RemoveChannelMessagesSent removes "channel_messages_sent" edges to ChannelMessage entities.
func (_u *UserUpdate) RemoveChannelMessagesSent(v ...*ChannelMessage) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMessagesSentIDs(ids...)
}

// ClearReceivedGroupKeys clears all "received_group_keys" edges to the GroupKey entity.
func (_u *UserUpdate) ClearReceivedGroupKeys() *UserUpdate {
	_u.mutation.ClearReceivedGroupKeys()
	return _u
}

// RemoveReceivedGroupKeyIDs removes the "received_group_keys" edge to GroupKey entities by IDs.
func (_u *UserUpdate) RemoveReceivedGroupKeyIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveReceivedGroupKeyIDs(ids...)
	return _u
}

// RemoveReceivedGroupKeys removes "received_group_keys" edges to GroupKey entities.
func (_u *UserUpdate) RemoveReceivedGroupKeys(v ...*GroupKey) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReceivedGroupKeyIDs(ids...)
}

// ClearSentGroupKeys clears all "sent_group_keys" edges to the GroupKey entity.
func (_u *UserUpdate) ClearSentGroupKeys() *UserUpdate {
	_u.mutation.ClearSentGroupKeys()
	return _u
}

// RemoveSentGroupKeyIDs removes the "sent_group_keys" edge to GroupKey entities by IDs.
func (_u *UserUpdate) RemoveSentGroupKeyIDs(ids ...string) *UserUpdate {
	_u.mutation.RemoveSentGroupKeyIDs(ids...)
	return _u
}

// RemoveSentGroupKeys removes "sent_group_keys" edges to GroupKey entities.
func (_u *UserUpdate) RemoveSentGroupKeys(v ...*GroupKey) *UserUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentGroupKeyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityKey(); ok {
		_spec.SetField(user.FieldIdentityKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SigningKey(); ok {
		_spec.SetField(user.FieldSigningKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(user.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AvatarMime(); ok {
		_spec.SetField(user.FieldAvatarMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarKey(); ok {
		_spec.SetField(user.FieldAvatarKey, field.TypeString, value)
	}
	if _u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.ChatsTable,
			Columns: user.ChatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatsIDs(); len(nodes) > 0 && !_u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.ChatsTable,
			Columns: user.ChatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.ChatsTable,
			Columns: user.ChatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MessagesTable,
			Columns: []string{user.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MessagesTable,
			Columns: []string{user.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MessagesTable,
			Columns: []string{user.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDevicesIDs(); len(nodes) > 0 && !_u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedChannelsTable,
			Columns: []string{user.OwnedChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedChannelsIDs(); len(nodes) > 0 && !_u.mutation.OwnedChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedChannelsTable,
			Columns: []string{user.OwnedChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedChannelsTable,
			Columns: []string{user.OwnedChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMembershipsTable,
			Columns: []string{user.ChannelMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMembershipsIDs(); len(nodes) > 0 && !_u.mutation.ChannelMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMembershipsTable,
			Columns: []string{user.ChannelMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMembershipsTable,
			Columns: []string{user.ChannelMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMessagesSentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMessagesSentTable,
			Columns: []string{user.ChannelMessagesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMessagesSentIDs(); len(nodes) > 0 && !_u.mutation.ChannelMessagesSentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMessagesSentTable,
			Columns: []string{user.ChannelMessagesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMessagesSentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMessagesSentTable,
			Columns: []string{user.ChannelMessagesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReceivedGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReceivedGroupKeysTable,
			Columns: []string{user.ReceivedGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReceivedGroupKeysIDs(); len(nodes) > 0 && !_u.mutation.ReceivedGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReceivedGroupKeysTable,
			Columns: []string{user.ReceivedGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceivedGroupKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReceivedGroupKeysTable,
			Columns: []string{user.ReceivedGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentGroupKeysTable,
			Columns: []string{user.SentGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentGroupKeysIDs(); len(nodes) > 0 && !_u.mutation.SentGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentGroupKeysTable,
			Columns: []string{user.SentGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentGroupKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentGroupKeysTable,
			Columns: []string{user.SentGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIdentityKey sets the "identity_key" field.
func (_u *UserUpdateOne) SetIdentityKey(v string) *UserUpdateOne {
	_u.mutation.SetIdentityKey(v)
	return _u
}

// SetNillableIdentityKey sets the "identity_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIdentityKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetIdentityKey(*v)
	}
	return _u
}

// SetSigningKey sets the "signing_key" field.
func (_u *UserUpdateOne) SetSigningKey(v string) *UserUpdateOne {
	_u.mutation.SetSigningKey(v)
	return _u
}

// SetNillableSigningKey sets the "signing_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSigningKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSigningKey(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *UserUpdateOne) SetLastSeen(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastSeen(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *UserUpdateOne) SetIsAdmin(v bool) *UserUpdateOne {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsAdmin(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetAvatarMime sets the "avatar_mime" field.
func (_u *UserUpdateOne) SetAvatarMime(v string) *UserUpdateOne {
	_u.mutation.SetAvatarMime(v)
	return _u
}

// SetNillableAvatarMime sets the "avatar_mime" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarMime(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarMime(*v)
	}
	return _u
}

// SetAvatarKey sets the "avatar_key" field.
func (_u *UserUpdateOne) SetAvatarKey(v string) *UserUpdateOne {
	_u.mutation.SetAvatarKey(v)
	return _u
}

// SetNillableAvatarKey sets the "avatar_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarKey(*v)
	}
	return _u
}

// AddChatIDs adds the "chats" edge to the Chat entity by IDs.
func (_u *UserUpdateOne) AddChatIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddChatIDs(ids...)
	return _u
}

// AddChats adds the "chats" edges to the Chat entity.
func (_u *UserUpdateOne) AddChats(v ...*Chat) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *UserUpdateOne) AddMessageIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *UserUpdateOne) AddMessages(v ...*Message) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *UserUpdateOne) AddAttachmentIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *UserUpdateOne) AddAttachments(v ...*Attachment) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_u *UserUpdateOne) AddDeviceIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.AddDeviceIDs(ids...)
	return _u
}

// AddDevices adds the "devices" edges to the Device entity.
func (_u *UserUpdateOne) AddDevices(v ...*Device) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeviceIDs(ids...)
}

// AddOwnedChannelIDs adds the "owned_channels" edge to the Channel entity by IDs.
func (_u *UserUpdateOne) AddOwnedChannelIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddOwnedChannelIDs(ids...)
	return _u
}

// AddOwnedChannels adds the "owned_channels" edges to the Channel entity.
func (_u *UserUpdateOne) AddOwnedChannels(v ...*Channel) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnedChannelIDs(ids...)
}

// AddChannelMembershipIDs adds the "channel_memberships" edge to the ChannelMember entity by IDs.
func (_u *UserUpdateOne) AddChannelMembershipIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddChannelMembershipIDs(ids...)
	return _u
}

// AddChannelMemberships adds the "channel_memberships" edges to the ChannelMember entity.
func (_u *UserUpdateOne) AddChannelMemberships(v ...*ChannelMember) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMembershipIDs(ids...)
}

// AddChannelMessagesSentIDs adds the "channel_messages_sent" edge to the ChannelMessage entity by IDs.
func (_u *UserUpdateOne) AddChannelMessagesSentIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.AddChannelMessagesSentIDs(ids...)
	return _u
}

// AddChannelMessagesSent adds the "channel_messages_sent" edges to the ChannelMessage entity.
func (_u *UserUpdateOne) AddChannelMessagesSent(v ...*ChannelMessage) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChannelMessagesSentIDs(ids...)
}

// AddReceivedGroupKeyIDs adds the "received_group_keys" edge to the GroupKey entity by IDs.
func (_u *UserUpdateOne) AddReceivedGroupKeyIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddReceivedGroupKeyIDs(ids...)
	return _u
}

// AddReceivedGroupKeys adds the "received_group_keys" edges to the GroupKey entity.
func (_u *UserUpdateOne) AddReceivedGroupKeys(v ...*GroupKey) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReceivedGroupKeyIDs(ids...)
}

// AddSentGroupKeyIDs adds the "sent_group_keys" edge to the GroupKey entity by IDs.
func (_u *UserUpdateOne) AddSentGroupKeyIDs(ids ...string) *UserUpdateOne {
	_u.mutation.AddSentGroupKeyIDs(ids...)
	return _u
}

// AddSentGroupKeys adds the "sent_group_keys" edges to the GroupKey entity.
func (_u *UserUpdateOne) AddSentGroupKeys(v ...*GroupKey) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSentGroupKeyIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearChats clears all "chats" edges to the Chat entity.
func (_u *UserUpdateOne) ClearChats() *UserUpdateOne {
	_u.mutation.ClearChats()
	return _u
}

// RemoveChatIDs removes the "chats" edge to Chat entities by IDs.
func (_u *UserUpdateOne) RemoveChatIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveChatIDs(ids...)
	return _u
}

// RemoveChats removes "chats" edges to Chat entities.
func (_u *UserUpdateOne) RemoveChats(v ...*Chat) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *UserUpdateOne) ClearMessages() *UserUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *UserUpdateOne) RemoveMessageIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *UserUpdateOne) RemoveMessages(v ...*Message) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *UserUpdateOne) ClearAttachments() *UserUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *UserUpdateOne) RemoveAttachmentIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *UserUpdateOne) RemoveAttachments(v ...*Attachment) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearDevices clears all "devices" edges to the Device entity.
func (_u *UserUpdateOne) ClearDevices() *UserUpdateOne {
	_u.mutation.ClearDevices()
	return _u
}

// RemoveDeviceIDs removes the "devices" edge to Device entities by IDs.
func (_u *UserUpdateOne) RemoveDeviceIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.RemoveDeviceIDs(ids...)
	return _u
}

// RemoveDevices removes "devices" edges to Device entities.
func (_u *UserUpdateOne) RemoveDevices(v ...*Device) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeviceIDs(ids...)
}

// ClearOwnedChannels clears all "owned_channels" edges to the Channel entity.
func (_u *UserUpdateOne) ClearOwnedChannels() *UserUpdateOne {
	_u.mutation.ClearOwnedChannels()
	return _u
}

// RemoveOwnedChannelIDs removes the "owned_channels" edge to Channel entities by IDs.
func (_u *UserUpdateOne) RemoveOwnedChannelIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveOwnedChannelIDs(ids...)
	return _u
}

// RemoveOwnedChannels removes "owned_channels" edges to Channel entities.
func (_u *UserUpdateOne) RemoveOwnedChannels(v ...*Channel) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnedChannelIDs(ids...)
}

// ClearChannelMemberships clears all "channel_memberships" edges to the ChannelMember entity.
func (_u *UserUpdateOne) ClearChannelMemberships() *UserUpdateOne {
	_u.mutation.ClearChannelMemberships()
	return _u
}

// RemoveChannelMembershipIDs removes the "channel_memberships" edge to ChannelMember entities by IDs.
func (_u *UserUpdateOne) RemoveChannelMembershipIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveChannelMembershipIDs(ids...)
	return _u
}

// RemoveChannelMemberships removes "channel_memberships" edges to ChannelMember entities.
func (_u *UserUpdateOne) RemoveChannelMemberships(v ...*ChannelMember) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMembershipIDs(ids...)
}

// ClearChannelMessagesSent clears all "channel_messages_sent" edges to the ChannelMessage entity.
func (_u *UserUpdateOne) ClearChannelMessagesSent() *UserUpdateOne {
	_u.mutation.ClearChannelMessagesSent()
	return _u
}

// RemoveChannelMessagesSentIDs removes the "channel_messages_sent" edge to ChannelMessage entities by IDs.
func (_u *UserUpdateOne) RemoveChannelMessagesSentIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.RemoveChannelMessagesSentIDs(ids...)
	return _u
}

// RemoveChannelMessagesSent removes "channel_messages_sent" edges to ChannelMessage entities.
func (_u *UserUpdateOne) RemoveChannelMessagesSent(v ...*ChannelMessage) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChannelMessagesSentIDs(ids...)
}

// ClearReceivedGroupKeys clears all "received_group_keys" edges to the GroupKey entity.
func (_u *UserUpdateOne) ClearReceivedGroupKeys() *UserUpdateOne {
	_u.mutation.ClearReceivedGroupKeys()
	return _u
}

// RemoveReceivedGroupKeyIDs removes the "received_group_keys" edge to GroupKey entities by IDs.
func (_u *UserUpdateOne) RemoveReceivedGroupKeyIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveReceivedGroupKeyIDs(ids...)
	return _u
}

// RemoveReceivedGroupKeys removes "received_group_keys" edges to GroupKey entities.
func (_u *UserUpdateOne) RemoveReceivedGroupKeys(v ...*GroupKey) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReceivedGroupKeyIDs(ids...)
}

// ClearSentGroupKeys clears all "sent_group_keys" edges to the GroupKey entity.
func (_u *UserUpdateOne) ClearSentGroupKeys() *UserUpdateOne {
	_u.mutation.ClearSentGroupKeys()
	return _u
}

// RemoveSentGroupKeyIDs removes the "sent_group_keys" edge to GroupKey entities by IDs.
func (_u *UserUpdateOne) RemoveSentGroupKeyIDs(ids ...string) *UserUpdateOne {
	_u.mutation.RemoveSentGroupKeyIDs(ids...)
	return _u
}

// RemoveSentGroupKeys removes "sent_group_keys" edges to GroupKey entities.
func (_u *UserUpdateOne) RemoveSentGroupKeys(v ...*GroupKey) *UserUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSentGroupKeyIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityKey(); ok {
		_spec.SetField(user.FieldIdentityKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SigningKey(); ok {
		_spec.SetField(user.FieldSigningKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(user.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AvatarMime(); ok {
		_spec.SetField(user.FieldAvatarMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarKey(); ok {
		_spec.SetField(user.FieldAvatarKey, field.TypeString, value)
	}
	if _u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.ChatsTable,
			Columns: user.ChatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatsIDs(); len(nodes) > 0 && !_u.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.ChatsTable,
			Columns: user.ChatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.ChatsTable,
			Columns: user.ChatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MessagesTable,
			Columns: []string{user.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MessagesTable,
			Columns: []string{user.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MessagesTable,
			Columns: []string{user.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttachmentsTable,
			Columns: []string{user.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDevicesIDs(); len(nodes) > 0 && !_u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnedChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedChannelsTable,
			Columns: []string{user.OwnedChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnedChannelsIDs(); len(nodes) > 0 && !_u.mutation.OwnedChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedChannelsTable,
			Columns: []string{user.OwnedChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnedChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedChannelsTable,
			Columns: []string{user.OwnedChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMembershipsTable,
			Columns: []string{user.ChannelMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMembershipsIDs(); len(nodes) > 0 && !_u.mutation.ChannelMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMembershipsTable,
			Columns: []string{user.ChannelMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMembershipsTable,
			Columns: []string{user.ChannelMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmember.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelMessagesSentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMessagesSentTable,
			Columns: []string{user.ChannelMessagesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChannelMessagesSentIDs(); len(nodes) > 0 && !_u.mutation.ChannelMessagesSentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMessagesSentTable,
			Columns: []string{user.ChannelMessagesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelMessagesSentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChannelMessagesSentTable,
			Columns: []string{user.ChannelMessagesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReceivedGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReceivedGroupKeysTable,
			Columns: []string{user.ReceivedGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReceivedGroupKeysIDs(); len(nodes) > 0 && !_u.mutation.ReceivedGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReceivedGroupKeysTable,
			Columns: []string{user.ReceivedGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceivedGroupKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReceivedGroupKeysTable,
			Columns: []string{user.ReceivedGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SentGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentGroupKeysTable,
			Columns: []string{user.SentGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSentGroupKeysIDs(); len(nodes) > 0 && !_u.mutation.SentGroupKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentGroupKeysTable,
			Columns: []string{user.SentGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SentGroupKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SentGroupKeysTable,
			Columns: []string{user.SentGroupKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupkey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
