// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"zuna.chat/zuna-server/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// IdentityKey holds the value of the "identity_key" field.
	IdentityKey string `json:"identity_key,omitempty"`
	// SigningKey holds the value of the "signing_key" field.
	SigningKey string `json:"signing_key,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen time.Time `json:"last_seen,omitempty"`
	// IsAdmin holds the value of the "is_admin" field.
	IsAdmin bool `json:"is_admin,omitempty"`
	// AvatarMime holds the value of the "avatar_mime" field.
	AvatarMime string `json:"avatar_mime,omitempty"`
	// AvatarKey holds the value of the "avatar_key" field.
	AvatarKey string `json:"avatar_key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Chats holds the value of the chats edge.
	Chats []*Chat `json:"chats,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// Devices holds the value of the devices edge.
	Devices []*Device `json:"devices,omitempty"`
	// OwnedChannels holds the value of the owned_channels edge.
	OwnedChannels []*Channel `json:"owned_channels,omitempty"`
	// ChannelMemberships holds the value of the channel_memberships edge.
	ChannelMemberships []*ChannelMember `json:"channel_memberships,omitempty"`
	// ChannelMessagesSent holds the value of the channel_messages_sent edge.
	ChannelMessagesSent []*ChannelMessage `json:"channel_messages_sent,omitempty"`
	// ReceivedGroupKeys holds the value of the received_group_keys edge.
	ReceivedGroupKeys []*GroupKey `json:"received_group_keys,omitempty"`
	// SentGroupKeys holds the value of the sent_group_keys edge.
	SentGroupKeys []*GroupKey `json:"sent_group_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [9]bool
}

// ChatsOrErr returns the Chats value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChatsOrErr() ([]*Chat, error) {
	if e.loadedTypes[0] {
		return e.Chats, nil
	}
	return nil, &NotLoadedError{edge: "chats"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[1] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[2] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// DevicesOrErr returns the Devices value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DevicesOrErr() ([]*Device, error) {
	if e.loadedTypes[3] {
		return e.Devices, nil
	}
	return nil, &NotLoadedError{edge: "devices"}
}

// OwnedChannelsOrErr returns the OwnedChannels value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OwnedChannelsOrErr() ([]*Channel, error) {
	if e.loadedTypes[4] {
		return e.OwnedChannels, nil
	}
	return nil, &NotLoadedError{edge: "owned_channels"}
}

// ChannelMembershipsOrErr returns the ChannelMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChannelMembershipsOrErr() ([]*ChannelMember, error) {
	if e.loadedTypes[5] {
		return e.ChannelMemberships, nil
	}
	return nil, &NotLoadedError{edge: "channel_memberships"}
}

// ChannelMessagesSentOrErr returns the ChannelMessagesSent value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChannelMessagesSentOrErr() ([]*ChannelMessage, error) {
	if e.loadedTypes[6] {
		return e.ChannelMessagesSent, nil
	}
	return nil, &NotLoadedError{edge: "channel_messages_sent"}
}

// ReceivedGroupKeysOrErr returns the ReceivedGroupKeys value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReceivedGroupKeysOrErr() ([]*GroupKey, error) {
	if e.loadedTypes[7] {
		return e.ReceivedGroupKeys, nil
	}
	return nil, &NotLoadedError{edge: "received_group_keys"}
}

// SentGroupKeysOrErr returns the SentGroupKeys value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentGroupKeysOrErr() ([]*GroupKey, error) {
	if e.loadedTypes[8] {
		return e.SentGroupKeys, nil
	}
	return nil, &NotLoadedError{edge: "sent_group_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsAdmin:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldUsername, user.FieldIdentityKey, user.FieldSigningKey, user.FieldAvatarMime, user.FieldAvatarKey:
			values[i] = new(sql.NullString)
		case user.FieldLastSeen:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldIdentityKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_key", values[i])
			} else if value.Valid {
				_m.IdentityKey = value.String
			}
		case user.FieldSigningKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signing_key", values[i])
			} else if value.Valid {
				_m.SigningKey = value.String
			}
		case user.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = value.Time
			}
		case user.FieldIsAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_admin", values[i])
			} else if value.Valid {
				_m.IsAdmin = value.Bool
			}
		case user.FieldAvatarMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_mime", values[i])
			} else if value.Valid {
				_m.AvatarMime = value.String
			}
		case user.FieldAvatarKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_key", values[i])
			} else if value.Valid {
				_m.AvatarKey = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChats queries the "chats" edge of the User entity.
func (_m *User) QueryChats() *ChatQuery {
	return NewUserClient(_m.config).QueryChats(_m)
}

// QueryMessages queries the "messages" edge of the User entity.
func (_m *User) QueryMessages() *MessageQuery {
	return NewUserClient(_m.config).QueryMessages(_m)
}

// QueryAttachments queries the "attachments" edge of the User entity.
func (_m *User) QueryAttachments() *AttachmentQuery {
	return NewUserClient(_m.config).QueryAttachments(_m)
}

// QueryDevices queries the "devices" edge of the User entity.
func (_m *User) QueryDevices() *DeviceQuery {
	return NewUserClient(_m.config).QueryDevices(_m)
}

// QueryOwnedChannels queries the "owned_channels" edge of the User entity.
func (_m *User) QueryOwnedChannels() *ChannelQuery {
	return NewUserClient(_m.config).QueryOwnedChannels(_m)
}

// QueryChannelMemberships queries the "channel_memberships" edge of the User entity.
func (_m *User) QueryChannelMemberships() *ChannelMemberQuery {
	return NewUserClient(_m.config).QueryChannelMemberships(_m)
}

// QueryChannelMessagesSent queries the "channel_messages_sent" edge of the User entity.
func (_m *User) QueryChannelMessagesSent() *ChannelMessageQuery {
	return NewUserClient(_m.config).QueryChannelMessagesSent(_m)
}

// QueryReceivedGroupKeys queries the "received_group_keys" edge of the User entity.
func (_m *User) QueryReceivedGroupKeys() *GroupKeyQuery {
	return NewUserClient(_m.config).QueryReceivedGroupKeys(_m)
}

// QuerySentGroupKeys queries the "sent_group_keys" edge of the User entity.
func (_m *User) QuerySentGroupKeys() *GroupKeyQuery {
	return NewUserClient(_m.config).QuerySentGroupKeys(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("identity_key=")
	builder.WriteString(_m.IdentityKey)
	builder.WriteString(", ")
	builder.WriteString("signing_key=")
	builder.WriteString(_m.SigningKey)
	builder.WriteString(", ")
	builder.WriteString("last_seen=")
	builder.WriteString(_m.LastSeen.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAdmin))
	builder.WriteString(", ")
	builder.WriteString("avatar_mime=")
	builder.WriteString(_m.AvatarMime)
	builder.WriteString(", ")
	builder.WriteString("avatar_key=")
	builder.WriteString(_m.AvatarKey)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
