// Code generated by ent, DO NOT EDIT.

package attachment

import (
	"zuna-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldID, id))
}

// SenderIdentityKey applies equality check predicate on the "sender_identity_key" field. It's identical to SenderIdentityKeyEQ.
func SenderIdentityKey(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldSenderIdentityKey, v))
}

// Iv applies equality check predicate on the "iv" field. It's identical to IvEQ.
func Iv(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldIv, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMimeType, v))
}

// OriginalFileName applies equality check predicate on the "original_file_name" field. It's identical to OriginalFileNameEQ.
func OriginalFileName(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldOriginalFileName, v))
}

// SenderIdentityKeyEQ applies the EQ predicate on the "sender_identity_key" field.
func SenderIdentityKeyEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyNEQ applies the NEQ predicate on the "sender_identity_key" field.
func SenderIdentityKeyNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyIn applies the In predicate on the "sender_identity_key" field.
func SenderIdentityKeyIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldSenderIdentityKey, vs...))
}

// SenderIdentityKeyNotIn applies the NotIn predicate on the "sender_identity_key" field.
func SenderIdentityKeyNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldSenderIdentityKey, vs...))
}

// SenderIdentityKeyGT applies the GT predicate on the "sender_identity_key" field.
func SenderIdentityKeyGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyGTE applies the GTE predicate on the "sender_identity_key" field.
func SenderIdentityKeyGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyLT applies the LT predicate on the "sender_identity_key" field.
func SenderIdentityKeyLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyLTE applies the LTE predicate on the "sender_identity_key" field.
func SenderIdentityKeyLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyContains applies the Contains predicate on the "sender_identity_key" field.
func SenderIdentityKeyContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyHasPrefix applies the HasPrefix predicate on the "sender_identity_key" field.
func SenderIdentityKeyHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyHasSuffix applies the HasSuffix predicate on the "sender_identity_key" field.
func SenderIdentityKeyHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyEqualFold applies the EqualFold predicate on the "sender_identity_key" field.
func SenderIdentityKeyEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldSenderIdentityKey, v))
}

// SenderIdentityKeyContainsFold applies the ContainsFold predicate on the "sender_identity_key" field.
func SenderIdentityKeyContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldSenderIdentityKey, v))
}

// IvEQ applies the EQ predicate on the "iv" field.
func IvEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldIv, v))
}

// IvNEQ applies the NEQ predicate on the "iv" field.
func IvNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldIv, v))
}

// IvIn applies the In predicate on the "iv" field.
func IvIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldIv, vs...))
}

// IvNotIn applies the NotIn predicate on the "iv" field.
func IvNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldIv, vs...))
}

// IvGT applies the GT predicate on the "iv" field.
func IvGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldIv, v))
}

// IvGTE applies the GTE predicate on the "iv" field.
func IvGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldIv, v))
}

// IvLT applies the LT predicate on the "iv" field.
func IvLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldIv, v))
}

// IvLTE applies the LTE predicate on the "iv" field.
func IvLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldIv, v))
}

// IvContains applies the Contains predicate on the "iv" field.
func IvContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldIv, v))
}

// IvHasPrefix applies the HasPrefix predicate on the "iv" field.
func IvHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldIv, v))
}

// IvHasSuffix applies the HasSuffix predicate on the "iv" field.
func IvHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldIv, v))
}

// IvEqualFold applies the EqualFold predicate on the "iv" field.
func IvEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldIv, v))
}

// IvContainsFold applies the ContainsFold predicate on the "iv" field.
func IvContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldIv, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldMimeType, v))
}

// OriginalFileNameEQ applies the EQ predicate on the "original_file_name" field.
func OriginalFileNameEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldOriginalFileName, v))
}

// OriginalFileNameNEQ applies the NEQ predicate on the "original_file_name" field.
func OriginalFileNameNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldOriginalFileName, v))
}

// OriginalFileNameIn applies the In predicate on the "original_file_name" field.
func OriginalFileNameIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldOriginalFileName, vs...))
}

// OriginalFileNameNotIn applies the NotIn predicate on the "original_file_name" field.
func OriginalFileNameNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldOriginalFileName, vs...))
}

// OriginalFileNameGT applies the GT predicate on the "original_file_name" field.
func OriginalFileNameGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldOriginalFileName, v))
}

// OriginalFileNameGTE applies the GTE predicate on the "original_file_name" field.
func OriginalFileNameGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldOriginalFileName, v))
}

// OriginalFileNameLT applies the LT predicate on the "original_file_name" field.
func OriginalFileNameLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldOriginalFileName, v))
}

// OriginalFileNameLTE applies the LTE predicate on the "original_file_name" field.
func OriginalFileNameLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldOriginalFileName, v))
}

// OriginalFileNameContains applies the Contains predicate on the "original_file_name" field.
func OriginalFileNameContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldOriginalFileName, v))
}

// OriginalFileNameHasPrefix applies the HasPrefix predicate on the "original_file_name" field.
func OriginalFileNameHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldOriginalFileName, v))
}

// OriginalFileNameHasSuffix applies the HasSuffix predicate on the "original_file_name" field.
func OriginalFileNameHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldOriginalFileName, v))
}

// OriginalFileNameEqualFold applies the EqualFold predicate on the "original_file_name" field.
func OriginalFileNameEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldOriginalFileName, v))
}

// OriginalFileNameContainsFold applies the ContainsFold predicate on the "original_file_name" field.
func OriginalFileNameContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldOriginalFileName, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.Message) predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.NotPredicates(p))
}
