// Code generated by ent, DO NOT EDIT.

package attachment

import (
	"zuna.chat/zuna-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldID, id))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMetadata, v))
}

// MetadataIv applies equality check predicate on the "metadata_iv" field. It's identical to MetadataIvEQ.
func MetadataIv(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMetadataIv, v))
}

// MetadataAuthTag applies equality check predicate on the "metadata_auth_tag" field. It's identical to MetadataAuthTagEQ.
func MetadataAuthTag(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMetadataAuthTag, v))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldMetadata, v))
}

// MetadataIvEQ applies the EQ predicate on the "metadata_iv" field.
func MetadataIvEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMetadataIv, v))
}

// MetadataIvNEQ applies the NEQ predicate on the "metadata_iv" field.
func MetadataIvNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldMetadataIv, v))
}

// MetadataIvIn applies the In predicate on the "metadata_iv" field.
func MetadataIvIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldMetadataIv, vs...))
}

// MetadataIvNotIn applies the NotIn predicate on the "metadata_iv" field.
func MetadataIvNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldMetadataIv, vs...))
}

// MetadataIvGT applies the GT predicate on the "metadata_iv" field.
func MetadataIvGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldMetadataIv, v))
}

// MetadataIvGTE applies the GTE predicate on the "metadata_iv" field.
func MetadataIvGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldMetadataIv, v))
}

// MetadataIvLT applies the LT predicate on the "metadata_iv" field.
func MetadataIvLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldMetadataIv, v))
}

// MetadataIvLTE applies the LTE predicate on the "metadata_iv" field.
func MetadataIvLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldMetadataIv, v))
}

// MetadataIvContains applies the Contains predicate on the "metadata_iv" field.
func MetadataIvContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldMetadataIv, v))
}

// MetadataIvHasPrefix applies the HasPrefix predicate on the "metadata_iv" field.
func MetadataIvHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldMetadataIv, v))
}

// MetadataIvHasSuffix applies the HasSuffix predicate on the "metadata_iv" field.
func MetadataIvHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldMetadataIv, v))
}

// MetadataIvEqualFold applies the EqualFold predicate on the "metadata_iv" field.
func MetadataIvEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldMetadataIv, v))
}

// MetadataIvContainsFold applies the ContainsFold predicate on the "metadata_iv" field.
func MetadataIvContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldMetadataIv, v))
}

// MetadataAuthTagEQ applies the EQ predicate on the "metadata_auth_tag" field.
func MetadataAuthTagEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEQ(FieldMetadataAuthTag, v))
}

// MetadataAuthTagNEQ applies the NEQ predicate on the "metadata_auth_tag" field.
func MetadataAuthTagNEQ(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNEQ(FieldMetadataAuthTag, v))
}

// MetadataAuthTagIn applies the In predicate on the "metadata_auth_tag" field.
func MetadataAuthTagIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldIn(FieldMetadataAuthTag, vs...))
}

// MetadataAuthTagNotIn applies the NotIn predicate on the "metadata_auth_tag" field.
func MetadataAuthTagNotIn(vs ...string) predicate.Attachment {
	return predicate.Attachment(sql.FieldNotIn(FieldMetadataAuthTag, vs...))
}

// MetadataAuthTagGT applies the GT predicate on the "metadata_auth_tag" field.
func MetadataAuthTagGT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGT(FieldMetadataAuthTag, v))
}

// MetadataAuthTagGTE applies the GTE predicate on the "metadata_auth_tag" field.
func MetadataAuthTagGTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldGTE(FieldMetadataAuthTag, v))
}

// MetadataAuthTagLT applies the LT predicate on the "metadata_auth_tag" field.
func MetadataAuthTagLT(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLT(FieldMetadataAuthTag, v))
}

// MetadataAuthTagLTE applies the LTE predicate on the "metadata_auth_tag" field.
func MetadataAuthTagLTE(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldLTE(FieldMetadataAuthTag, v))
}

// MetadataAuthTagContains applies the Contains predicate on the "metadata_auth_tag" field.
func MetadataAuthTagContains(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContains(FieldMetadataAuthTag, v))
}

// MetadataAuthTagHasPrefix applies the HasPrefix predicate on the "metadata_auth_tag" field.
func MetadataAuthTagHasPrefix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasPrefix(FieldMetadataAuthTag, v))
}

// MetadataAuthTagHasSuffix applies the HasSuffix predicate on the "metadata_auth_tag" field.
func MetadataAuthTagHasSuffix(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldHasSuffix(FieldMetadataAuthTag, v))
}

// MetadataAuthTagEqualFold applies the EqualFold predicate on the "metadata_auth_tag" field.
func MetadataAuthTagEqualFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldEqualFold(FieldMetadataAuthTag, v))
}

// MetadataAuthTagContainsFold applies the ContainsFold predicate on the "metadata_auth_tag" field.
func MetadataAuthTagContainsFold(v string) predicate.Attachment {
	return predicate.Attachment(sql.FieldContainsFold(FieldMetadataAuthTag, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.Message) predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Attachment {
	return predicate.Attachment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Attachment) predicate.Attachment {
	return predicate.Attachment(sql.NotPredicates(p))
}
