// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttachmentsColumns holds the columns for the "attachments" table.
	AttachmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "sender_identity_key", Type: field.TypeString},
		{Name: "iv", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "original_file_name", Type: field.TypeString},
		{Name: "message_attachments", Type: field.TypeInt64},
	}
	// AttachmentsTable holds the schema information for the "attachments" table.
	AttachmentsTable = &schema.Table{
		Name:       "attachments",
		Columns:    AttachmentsColumns,
		PrimaryKey: []*schema.Column{AttachmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attachments_messages_attachments",
				Columns:    []*schema.Column{AttachmentsColumns[5]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChatsColumns holds the columns for the "chats" table.
	ChatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
	}
	// ChatsTable holds the schema information for the "chats" table.
	ChatsTable = &schema.Table{
		Name:       "chats",
		Columns:    ChatsColumns,
		PrimaryKey: []*schema.Column{ChatsColumns[0]},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "cipher_text", Type: field.TypeString, SchemaType: map[string]string{"mysql": "mediumtext"}},
		{Name: "iv", Type: field.TypeString},
		{Name: "auth_tag", Type: field.TypeString},
		{Name: "sent_at", Type: field.TypeTime},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "chat_messages", Type: field.TypeString},
		{Name: "user_messages", Type: field.TypeString},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_chats_messages",
				Columns:    []*schema.Column{MessagesColumns[6]},
				RefColumns: []*schema.Column{ChatsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "messages_users_messages",
				Columns:    []*schema.Column{MessagesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "identity_key", Type: field.TypeString, Unique: true},
		{Name: "signing_key", Type: field.TypeString, Unique: true},
		{Name: "last_seen", Type: field.TypeTime},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "avatar_key", Type: field.TypeString, Default: ""},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserChatsColumns holds the columns for the "user_chats" table.
	UserChatsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString},
		{Name: "chat_id", Type: field.TypeString},
	}
	// UserChatsTable holds the schema information for the "user_chats" table.
	UserChatsTable = &schema.Table{
		Name:       "user_chats",
		Columns:    UserChatsColumns,
		PrimaryKey: []*schema.Column{UserChatsColumns[0], UserChatsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_chats_user_id",
				Columns:    []*schema.Column{UserChatsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_chats_chat_id",
				Columns:    []*schema.Column{UserChatsColumns[1]},
				RefColumns: []*schema.Column{ChatsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttachmentsTable,
		ChatsTable,
		MessagesTable,
		UsersTable,
		UserChatsTable,
	}
)

func init() {
	AttachmentsTable.ForeignKeys[0].RefTable = MessagesTable
	MessagesTable.ForeignKeys[0].RefTable = ChatsTable
	MessagesTable.ForeignKeys[1].RefTable = UsersTable
	UserChatsTable.ForeignKeys[0].RefTable = UsersTable
	UserChatsTable.ForeignKeys[1].RefTable = ChatsTable
}
