// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldIdentityKey holds the string denoting the identity_key field in the database.
	FieldIdentityKey = "identity_key"
	// FieldSigningKey holds the string denoting the signing_key field in the database.
	FieldSigningKey = "signing_key"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldIsAdmin holds the string denoting the is_admin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldAvatarMime holds the string denoting the avatar_mime field in the database.
	FieldAvatarMime = "avatar_mime"
	// FieldAvatarKey holds the string denoting the avatar_key field in the database.
	FieldAvatarKey = "avatar_key"
	// EdgeChats holds the string denoting the chats edge name in mutations.
	EdgeChats = "chats"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// EdgeAttachments holds the string denoting the attachments edge name in mutations.
	EdgeAttachments = "attachments"
	// EdgeDevices holds the string denoting the devices edge name in mutations.
	EdgeDevices = "devices"
	// EdgeOwnedChannels holds the string denoting the owned_channels edge name in mutations.
	EdgeOwnedChannels = "owned_channels"
	// EdgeChannelMemberships holds the string denoting the channel_memberships edge name in mutations.
	EdgeChannelMemberships = "channel_memberships"
	// EdgeChannelMessagesSent holds the string denoting the channel_messages_sent edge name in mutations.
	EdgeChannelMessagesSent = "channel_messages_sent"
	// EdgeReceivedGroupKeys holds the string denoting the received_group_keys edge name in mutations.
	EdgeReceivedGroupKeys = "received_group_keys"
	// EdgeSentGroupKeys holds the string denoting the sent_group_keys edge name in mutations.
	EdgeSentGroupKeys = "sent_group_keys"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ChatsTable is the table that holds the chats relation/edge. The primary key declared below.
	ChatsTable = "user_chats"
	// ChatsInverseTable is the table name for the Chat entity.
	// It exists in this package in order to avoid circular dependency with the "chat" package.
	ChatsInverseTable = "chats"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "messages"
	// MessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessagesInverseTable = "messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "user_messages"
	// AttachmentsTable is the table that holds the attachments relation/edge.
	AttachmentsTable = "attachments"
	// AttachmentsInverseTable is the table name for the Attachment entity.
	// It exists in this package in order to avoid circular dependency with the "attachment" package.
	AttachmentsInverseTable = "attachments"
	// AttachmentsColumn is the table column denoting the attachments relation/edge.
	AttachmentsColumn = "user_attachments"
	// DevicesTable is the table that holds the devices relation/edge.
	DevicesTable = "devices"
	// DevicesInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DevicesInverseTable = "devices"
	// DevicesColumn is the table column denoting the devices relation/edge.
	DevicesColumn = "user_devices"
	// OwnedChannelsTable is the table that holds the owned_channels relation/edge.
	OwnedChannelsTable = "channels"
	// OwnedChannelsInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	OwnedChannelsInverseTable = "channels"
	// OwnedChannelsColumn is the table column denoting the owned_channels relation/edge.
	OwnedChannelsColumn = "user_owned_channels"
	// ChannelMembershipsTable is the table that holds the channel_memberships relation/edge.
	ChannelMembershipsTable = "channel_members"
	// ChannelMembershipsInverseTable is the table name for the ChannelMember entity.
	// It exists in this package in order to avoid circular dependency with the "channelmember" package.
	ChannelMembershipsInverseTable = "channel_members"
	// ChannelMembershipsColumn is the table column denoting the channel_memberships relation/edge.
	ChannelMembershipsColumn = "user_channel_memberships"
	// ChannelMessagesSentTable is the table that holds the channel_messages_sent relation/edge.
	ChannelMessagesSentTable = "channel_messages"
	// ChannelMessagesSentInverseTable is the table name for the ChannelMessage entity.
	// It exists in this package in order to avoid circular dependency with the "channelmessage" package.
	ChannelMessagesSentInverseTable = "channel_messages"
	// ChannelMessagesSentColumn is the table column denoting the channel_messages_sent relation/edge.
	ChannelMessagesSentColumn = "user_channel_messages_sent"
	// ReceivedGroupKeysTable is the table that holds the received_group_keys relation/edge.
	ReceivedGroupKeysTable = "group_keys"
	// ReceivedGroupKeysInverseTable is the table name for the GroupKey entity.
	// It exists in this package in order to avoid circular dependency with the "groupkey" package.
	ReceivedGroupKeysInverseTable = "group_keys"
	// ReceivedGroupKeysColumn is the table column denoting the received_group_keys relation/edge.
	ReceivedGroupKeysColumn = "user_received_group_keys"
	// SentGroupKeysTable is the table that holds the sent_group_keys relation/edge.
	SentGroupKeysTable = "group_keys"
	// SentGroupKeysInverseTable is the table name for the GroupKey entity.
	// It exists in this package in order to avoid circular dependency with the "groupkey" package.
	SentGroupKeysInverseTable = "group_keys"
	// SentGroupKeysColumn is the table column denoting the sent_group_keys relation/edge.
	SentGroupKeysColumn = "user_sent_group_keys"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldIdentityKey,
	FieldSigningKey,
	FieldLastSeen,
	FieldIsAdmin,
	FieldAvatarMime,
	FieldAvatarKey,
}

var (
	// ChatsPrimaryKey and ChatsColumn2 are the table columns denoting the
	// primary key for the chats relation (M2M).
	ChatsPrimaryKey = []string{"user_id", "chat_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastSeen holds the default value on creation for the "last_seen" field.
	DefaultLastSeen func() time.Time
	// DefaultIsAdmin holds the default value on creation for the "is_admin" field.
	DefaultIsAdmin bool
	// DefaultAvatarMime holds the default value on creation for the "avatar_mime" field.
	DefaultAvatarMime string
	// DefaultAvatarKey holds the default value on creation for the "avatar_key" field.
	DefaultAvatarKey string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByIdentityKey orders the results by the identity_key field.
func ByIdentityKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityKey, opts...).ToFunc()
}

// BySigningKey orders the results by the signing_key field.
func BySigningKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSigningKey, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByIsAdmin orders the results by the is_admin field.
func ByIsAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdmin, opts...).ToFunc()
}

// ByAvatarMime orders the results by the avatar_mime field.
func ByAvatarMime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarMime, opts...).ToFunc()
}

// ByAvatarKey orders the results by the avatar_key field.
func ByAvatarKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarKey, opts...).ToFunc()
}

// ByChatsCount orders the results by chats count.
func ByChatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChatsStep(), opts...)
	}
}

// ByChats orders the results by chats terms.
func ByChats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttachmentsCount orders the results by attachments count.
func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
	}
}

// ByAttachments orders the results by attachments terms.
func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDevicesCount orders the results by devices count.
func ByDevicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDevicesStep(), opts...)
	}
}

// ByDevices orders the results by devices terms.
func ByDevices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDevicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOwnedChannelsCount orders the results by owned_channels count.
func ByOwnedChannelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOwnedChannelsStep(), opts...)
	}
}

// ByOwnedChannels orders the results by owned_channels terms.
func ByOwnedChannels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnedChannelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChannelMembershipsCount orders the results by channel_memberships count.
func ByChannelMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelMembershipsStep(), opts...)
	}
}

// ByChannelMemberships orders the results by channel_memberships terms.
func ByChannelMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChannelMessagesSentCount orders the results by channel_messages_sent count.
func ByChannelMessagesSentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChannelMessagesSentStep(), opts...)
	}
}

// ByChannelMessagesSent orders the results by channel_messages_sent terms.
func ByChannelMessagesSent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelMessagesSentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReceivedGroupKeysCount orders the results by received_group_keys count.
func ByReceivedGroupKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReceivedGroupKeysStep(), opts...)
	}
}

// ByReceivedGroupKeys orders the results by received_group_keys terms.
func ByReceivedGroupKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReceivedGroupKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySentGroupKeysCount orders the results by sent_group_keys count.
func BySentGroupKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSentGroupKeysStep(), opts...)
	}
}

// BySentGroupKeys orders the results by sent_group_keys terms.
func BySentGroupKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSentGroupKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ChatsTable, ChatsPrimaryKey...),
	)
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
func newAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
	)
}
func newDevicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DevicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
	)
}
func newOwnedChannelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnedChannelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OwnedChannelsTable, OwnedChannelsColumn),
	)
}
func newChannelMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelMembershipsTable, ChannelMembershipsColumn),
	)
}
func newChannelMessagesSentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelMessagesSentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChannelMessagesSentTable, ChannelMessagesSentColumn),
	)
}
func newReceivedGroupKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReceivedGroupKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReceivedGroupKeysTable, ReceivedGroupKeysColumn),
	)
}
func newSentGroupKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SentGroupKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SentGroupKeysTable, SentGroupKeysColumn),
	)
}
