// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"
	"zuna-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// IdentityKey applies equality check predicate on the "identity_key" field. It's identical to IdentityKeyEQ.
func IdentityKey(v []byte) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIdentityKey, v))
}

// SigningKey applies equality check predicate on the "signing_key" field. It's identical to SigningKeyEQ.
func SigningKey(v []byte) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSigningKey, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastSeen, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// Avatar applies equality check predicate on the "avatar" field. It's identical to AvatarEQ.
func Avatar(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatar, v))
}

// AvatarIv applies equality check predicate on the "avatar_iv" field. It's identical to AvatarIvEQ.
func AvatarIv(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarIv, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// IdentityKeyEQ applies the EQ predicate on the "identity_key" field.
func IdentityKeyEQ(v []byte) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIdentityKey, v))
}

// IdentityKeyNEQ applies the NEQ predicate on the "identity_key" field.
func IdentityKeyNEQ(v []byte) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIdentityKey, v))
}

// IdentityKeyIn applies the In predicate on the "identity_key" field.
func IdentityKeyIn(vs ...[]byte) predicate.User {
	return predicate.User(sql.FieldIn(FieldIdentityKey, vs...))
}

// IdentityKeyNotIn applies the NotIn predicate on the "identity_key" field.
func IdentityKeyNotIn(vs ...[]byte) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldIdentityKey, vs...))
}

// IdentityKeyGT applies the GT predicate on the "identity_key" field.
func IdentityKeyGT(v []byte) predicate.User {
	return predicate.User(sql.FieldGT(FieldIdentityKey, v))
}

// IdentityKeyGTE applies the GTE predicate on the "identity_key" field.
func IdentityKeyGTE(v []byte) predicate.User {
	return predicate.User(sql.FieldGTE(FieldIdentityKey, v))
}

// IdentityKeyLT applies the LT predicate on the "identity_key" field.
func IdentityKeyLT(v []byte) predicate.User {
	return predicate.User(sql.FieldLT(FieldIdentityKey, v))
}

// IdentityKeyLTE applies the LTE predicate on the "identity_key" field.
func IdentityKeyLTE(v []byte) predicate.User {
	return predicate.User(sql.FieldLTE(FieldIdentityKey, v))
}

// SigningKeyEQ applies the EQ predicate on the "signing_key" field.
func SigningKeyEQ(v []byte) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSigningKey, v))
}

// SigningKeyNEQ applies the NEQ predicate on the "signing_key" field.
func SigningKeyNEQ(v []byte) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSigningKey, v))
}

// SigningKeyIn applies the In predicate on the "signing_key" field.
func SigningKeyIn(vs ...[]byte) predicate.User {
	return predicate.User(sql.FieldIn(FieldSigningKey, vs...))
}

// SigningKeyNotIn applies the NotIn predicate on the "signing_key" field.
func SigningKeyNotIn(vs ...[]byte) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSigningKey, vs...))
}

// SigningKeyGT applies the GT predicate on the "signing_key" field.
func SigningKeyGT(v []byte) predicate.User {
	return predicate.User(sql.FieldGT(FieldSigningKey, v))
}

// SigningKeyGTE applies the GTE predicate on the "signing_key" field.
func SigningKeyGTE(v []byte) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSigningKey, v))
}

// SigningKeyLT applies the LT predicate on the "signing_key" field.
func SigningKeyLT(v []byte) predicate.User {
	return predicate.User(sql.FieldLT(FieldSigningKey, v))
}

// SigningKeyLTE applies the LTE predicate on the "signing_key" field.
func SigningKeyLTE(v []byte) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSigningKey, v))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastSeen, v))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsAdmin, v))
}

// AvatarEQ applies the EQ predicate on the "avatar" field.
func AvatarEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatar, v))
}

// AvatarNEQ applies the NEQ predicate on the "avatar" field.
func AvatarNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatar, v))
}

// AvatarIn applies the In predicate on the "avatar" field.
func AvatarIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatar, vs...))
}

// AvatarNotIn applies the NotIn predicate on the "avatar" field.
func AvatarNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatar, vs...))
}

// AvatarGT applies the GT predicate on the "avatar" field.
func AvatarGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatar, v))
}

// AvatarGTE applies the GTE predicate on the "avatar" field.
func AvatarGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatar, v))
}

// AvatarLT applies the LT predicate on the "avatar" field.
func AvatarLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatar, v))
}

// AvatarLTE applies the LTE predicate on the "avatar" field.
func AvatarLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatar, v))
}

// AvatarContains applies the Contains predicate on the "avatar" field.
func AvatarContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatar, v))
}

// AvatarHasPrefix applies the HasPrefix predicate on the "avatar" field.
func AvatarHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatar, v))
}

// AvatarHasSuffix applies the HasSuffix predicate on the "avatar" field.
func AvatarHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatar, v))
}

// AvatarIsNil applies the IsNil predicate on the "avatar" field.
func AvatarIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatar))
}

// AvatarNotNil applies the NotNil predicate on the "avatar" field.
func AvatarNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatar))
}

// AvatarEqualFold applies the EqualFold predicate on the "avatar" field.
func AvatarEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatar, v))
}

// AvatarContainsFold applies the ContainsFold predicate on the "avatar" field.
func AvatarContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatar, v))
}

// AvatarIvEQ applies the EQ predicate on the "avatar_iv" field.
func AvatarIvEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarIv, v))
}

// AvatarIvNEQ applies the NEQ predicate on the "avatar_iv" field.
func AvatarIvNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarIv, v))
}

// AvatarIvIn applies the In predicate on the "avatar_iv" field.
func AvatarIvIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarIv, vs...))
}

// AvatarIvNotIn applies the NotIn predicate on the "avatar_iv" field.
func AvatarIvNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarIv, vs...))
}

// AvatarIvGT applies the GT predicate on the "avatar_iv" field.
func AvatarIvGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarIv, v))
}

// AvatarIvGTE applies the GTE predicate on the "avatar_iv" field.
func AvatarIvGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarIv, v))
}

// AvatarIvLT applies the LT predicate on the "avatar_iv" field.
func AvatarIvLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarIv, v))
}

// AvatarIvLTE applies the LTE predicate on the "avatar_iv" field.
func AvatarIvLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarIv, v))
}

// AvatarIvContains applies the Contains predicate on the "avatar_iv" field.
func AvatarIvContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarIv, v))
}

// AvatarIvHasPrefix applies the HasPrefix predicate on the "avatar_iv" field.
func AvatarIvHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarIv, v))
}

// AvatarIvHasSuffix applies the HasSuffix predicate on the "avatar_iv" field.
func AvatarIvHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarIv, v))
}

// AvatarIvIsNil applies the IsNil predicate on the "avatar_iv" field.
func AvatarIvIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarIv))
}

// AvatarIvNotNil applies the NotNil predicate on the "avatar_iv" field.
func AvatarIvNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarIv))
}

// AvatarIvEqualFold applies the EqualFold predicate on the "avatar_iv" field.
func AvatarIvEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarIv, v))
}

// AvatarIvContainsFold applies the ContainsFold predicate on the "avatar_iv" field.
func AvatarIvContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarIv, v))
}

// HasChats applies the HasEdge predicate on the "chats" edge.
func HasChats() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ChatsTable, ChatsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatsWith applies the HasEdge predicate on the "chats" edge with a given conditions (other predicates).
func HasChatsWith(preds ...predicate.Chat) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newChatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
